/*;=============================================   
; Author           :  Global Software's    
; Create date      :  17/08/2022    
; Create By        :  ASLAM  
; Description      :  QUERY
; Change Person    :  SWETHA
; Last Change Date :  24/07/2024 10.00 AM 
; =============================================  */  
CREATE PROCEDURE SP_DEBITQRY_2 (@Ordid int,@DeptId int) as 
 SELECT CountName,YF,ColorDesc,ShortMill,Fabdesc,Acc_Descr,AccDescription,billtype, sum(kg) as kg,Rate,sum(Amount) as Amount,Sum(Amt) as Amt,Id,Sum(Netamt) as NetAmt,UOM FROM (  SELECT CountName,YF,ColorDesc,ShortMill,Fabdesc,Acc_Descr,AccDescription,billtype,sum(debkg) as kg, Case When IsNull(BillType,'')='Purchase' Then Case When IsNull(Fcy,0)>0 Then ISNULL(Rate, 0)  * IsNull(exchangeRate,0)  else  ISNULL(Rate, 0) end else  ISNULL(Rate, 0) end  AS Rate, Case When IsNull(BillType,'')='Purchase' Then Case When IsNull(Fcy,0)>0 Then isnull(DebKg,0) * isnull( Rate,0) * IsNull(exchangeRate,0)  else  isnull(DebKg,0) * isnull( Rate,0) end else  isnull(DebKg,0) * isnull( Rate,0) end  AS Amount,isnull(Sum(DebitValue),0) as Amt,ID, Case When IsNull(BillType,'')='Purchase' Then Case When IsNull(Fcy,0)>0 Then isnull(sum(NetAmt),0)  * IsNull(exchangeRate,0)  else  isnull(sum(NetAmt),0)  end else  isnull(sum(NetAmt),0) end  as NetAmt,UOM FROM ( SELECT DISTINCT Mas_Count.CountName, StockTable.YF, Mas_Color.ColorDesc, Mas_Mill.ShortMill, Mas_Fabric.Fabdesc, Mas_Acc.Acc_Descr, Mas_AccDes.AccDescription,billtype,isnull(Trs_Deb2.DebKg,0) as DebKg,Trs_Deb2.Rate,trs_deb1.fcy,isnull(exchangeRate,0) as exchangerate,Trs_Deb1.DebitValue,trs_deb1.id,trs_deb2.NetAmt,CASE WHEN Mas_Fabric.Fabdesc <> '' THEN Mas_Uom.Uom ELSE UOM1.Uom END AS UOM FROM Mas_AccDes RIGHT OUTER JOIN Trs_Deb1 INNER JOIN Trs_Deb2 ON Trs_Deb1.ID = Trs_Deb2.ID LEFT OUTER JOIN StockTable ON Trs_Deb2.StockID = StockTable.StockID ON Mas_AccDes.ID = StockTable.Ades LEFT OUTER JOIN Mas_Acc ON Mas_AccDes.AccTypeID = Mas_Acc.ID AND StockTable.Atype = Mas_Acc.ID LEFT OUTER JOIN Mas_Count ON StockTable.CntID = Mas_Count.CountID LEFT OUTER JOIN Mas_Fabric ON StockTable.FabID = Mas_Fabric.FabID LEFT OUTER JOIN Mas_Mill ON StockTable.MillID = Mas_Mill.MillID LEFT OUTER JOIN Mas_Color ON StockTable.ColID = Mas_Color.ColID LEFT OUTER JOIN (SELECT distinct OrdId,DeptId,FabId,CntID,ColId,RateUOM FROM Pro_ReqKnitt2) Y on Y.OrdId = Trs_Deb1.OrdID AND Y.FabId = StockTable.Fabid and Y.DeptId = Trs_Deb1.Dept and Y.CntID = StockTable.Cntid and Y.ColId = StockTable.ColId LEFT OUTER JOIN Mas_Uom ON Mas_Uom.UomID = Mas_Fabric.PriUomID LEFT OUTER JOIN Mas_Uom AS UOM1 ON UOM1.UomID = Mas_Acc.UomId INNER JOIN  (Select distinct Trs_Bills.id,PoID,BillType from Trs_Bills  INNER JOIN  Trs_BillRate ON Trs_BillRate.ID = Trs_Bills.ID Where ORdid = @Ordid  ) Trs_Bills on Trs_Deb1.Brnid = Trs_Bills.ID  Left Join Trs_Po1 On Trs_Bills.PoId=Trs_Po1.Id  WHERE  Trs_Deb2.Ordid=@ORdid and trs_deb1.Dept=@DeptID )X GROUP BY  CountName,  ColorDesc,  ShortMill,  Fabdesc,  Acc_Descr, AccDescription,  rate,YF,Isnull(DebitValue,0), ID,isnull(DebKg,0),isnull( Rate,0) ,BillType,exchangeRate,Fcy,UOM ) YY GROUP BY CountName,YF,ColorDesc,ShortMill,Fabdesc,Acc_Descr,AccDescription,billtype, Rate,ID,UOM
 
