/*;=============================================   
; Author           :  Global Software's    
; Create date      :  17/08/2022    
; Create By        :  ASLAM  
; Description      :  QUERY
; Change Person    :  ASLAM
; Last Change Date :  16/12/2022 10.12 AM 
; =============================================  */  
CREATE PROCEDURE SP_PartwiseRequirement (@txtID int,@StyleNo_1  NVARCHAR(1000))
AS
BEGIN 
SELECT OrderMas.Jobno, OrderMas.Finyear, OrderMas.BuyOrdNo,Mas_Acc.Acc_Descr, Mas_AccDes.AccDescription,Mas_Color.ColorDesc,Mas_Size.SizeDesc, Sum(PRO_AccReq.ReqdQty) AS ReqdQty, Mas_Uom.Uom, Min(PRO_AccReq.SlNo) SlNo, PRO_AccReq.StyleNo, PRO_AccReq.Siz,ISNULL(PRO_AccReq.LotNo,'') as LotNo,Avg(PRO_AccReq.Req) as Req,Avg(PRO_AccReq.Pcs) as Pcs,Avg(PRO_AccReq.Excess) as Excess,Sum(PRO_AccReq.OrdQty) as OrdQty,OrdSizeMas.SNo,Pro_AccReq.ItemBlockin_PO ,OrderMAs.OrderType,'' as process,IsNull(Mas_AccCategory.CatName,'') As CatName,'' as ClrComboDesc FROM Mas_AccDes RIGHT OUTER JOIN Mas_Uom RIGHT OUTER JOIN Mas_Size RIGHT OUTER JOIN PRO_AccReq INNER JOIN Mas_Acc ON PRO_AccReq.Acc_Type = Mas_Acc.ID INNER JOIN OrderMas ON PRO_AccReq.OrdID = OrderMas.OrdId LEFT OUTER JOIN OrdSizeMas ON PRO_AccReq.OrdID = OrdSizeMas.OrdID AND PRO_AccReq.Siz = OrdSizeMas.SizeId AND Pro_AccReq.StyleNo = OrdSizeMas.StyleNo ON Mas_Size.SizeID = PRO_AccReq.Siz LEFT OUTER JOIN Mas_Color ON PRO_AccReq.Clr = Mas_Color.ColID ON Mas_Uom.UomID = Mas_Acc.UomId ON Mas_AccDes.ID = PRO_AccReq.Acc_Desc AND Mas_AccDes.AccTypeID = Mas_Acc.ID Left Join Mas_AccCategory On Mas_Acc.CatId=Mas_AccCategory.CatId   WHERE PRO_AccReq.OrdID = @txtID AND PRO_AccReq.StyleNo = @StyleNo_1 and ItemType='M' and SewFlg is null GROUP BY OrderMas.Jobno, OrderMas.Finyear, OrderMas.BuyOrdNo, Mas_Acc.Acc_Descr, Mas_AccDes.AccDescription, Mas_Color.ColorDesc, Mas_Size.SizeDesc, Mas_Uom.Uom, PRO_AccReq.StyleNo, PRO_AccReq.Siz,ISNULL(PRO_AccReq.LotNo,''),OrdSizeMas.SNo,Pro_AccReq.ItemBlockin_PO ,OrderMAs.OrderType,Mas_AccCategory.CatName UNION SELECT OrderMas.Jobno, OrderMas.Finyear, OrderMas.BuyOrdNo,Mas_Acc.Acc_Descr, Mas_AccDes.AccDescription,Mas_Color.ColorDesc,Mas_Size.SizeDesc, Sum(PRO_AccReq.ReqdQty) AS ReqdQty, Mas_Uom.Uom, Min(PRO_AccReq.SlNo) SlNo, PRO_AccReq.StyleNo, PRO_AccReq.Siz,ISNULL(PRO_AccReq.LotNo,'') as LotNo,Avg(PRO_AccReq.Req) as Req,Avg(PRO_AccReq.Pcs) as Pcs,Avg(PRO_AccReq.Excess) as Excess,Sum(distinct PRO_AccReq.OrdQty) as OrdQty,OrdSizeMas.SNo,Pro_AccReq.ItemBlockin_PO ,OrderMAs.OrderType,'' as process,IsNull(Mas_AccCategory.CatName,'') As CatName,'' as ClrComboDesc FROM Mas_AccDes RIGHT OUTER JOIN Mas_Uom RIGHT OUTER JOIN Mas_Size RIGHT OUTER JOIN PRO_AccReq INNER JOIN Mas_Acc ON PRO_AccReq.Acc_Type = Mas_Acc.ID INNER JOIN OrderMas ON PRO_AccReq.OrdID = OrderMas.OrdId LEFT OUTER JOIN OrdSizeMas ON PRO_AccReq.OrdID = OrdSizeMas.OrdID AND PRO_AccReq.Siz = OrdSizeMas.SizeId And Pro_AccReq.StyleNo = OrdSizeMas.StyleNo ON Mas_Size.SizeID = PRO_AccReq.Siz LEFT OUTER JOIN Mas_Color ON PRO_AccReq.Clr = Mas_Color.ColID ON Mas_Uom.UomID = Mas_Acc.UomId ON Mas_AccDes.ID = PRO_AccReq.Acc_Desc AND Mas_AccDes.AccTypeID = Mas_Acc.ID Left Join Mas_AccCategory On Mas_Acc.CatId=Mas_AccCategory.CatId WHERE PRO_AccReq.OrdID = @txtID AND PRO_AccReq.StyleNo = @StyleNo_1 and ItemType='M' and sewflg=1 GROUP BY OrderMas.Jobno, OrderMas.Finyear, OrderMas.BuyOrdNo, Mas_Acc.Acc_Descr,
 Mas_AccDes.AccDescription, Mas_Color.ColorDesc, Mas_Size.SizeDesc, Mas_Uom.Uom, PRO_AccReq.StyleNo, PRO_AccReq.Siz,ISNULL(PRO_AccReq.LotNo,''),OrdSizeMas.SNo,Pro_AccReq.ItemBlockin_PO ,OrderMAs.OrderType,Mas_AccCategory.CatName ORDER BY isnull(PRO_AccReq.LotNo,'') ,Slno,OrdSizeMas.SNo

 END

 