

/*;=============================================   

; Author           :  Global Software's    

; Create date      :  20/08/2008    

; Create By        :  ASLAM  

; Description      :  BudgetActual  

; Change Person    :  Suganya

; Last Change Date :  02/03/2024 12.45 PM 

; =============================================  */  

CREATE VIEW VUE_RPT_BUDABS_StyleWise AS  

SELECT CASE WHEN (GrpRef = 0 OR GrpREf IS NULL) THEN Pro_ReqYarn.OrdID ELSE GrpRef END AS GrpOrdID, Pro_ReqYarn.OrdId, Pro_ReqYarn.StyleNo,Mas_Dept.Deptname,  Mas_Dept.OrderSno, Case  When isnull(Mas_Dept.Manual_BudgetKGs_Entry,'N')='Y' then ISNULL(SUM(IsNull(Pro_ReqYarn2.Qty,0) * CASE WHEN (GrpRef = 0 OR GrpREf IS NULL) THEN Pro_ReqYarn2.Rate else Pro_ReqYarn2_Grp.Rate end ), 0) Else ISNULL(SUM(Pro_ReqYarn.ReqKgs * CASE WHEN (GrpRef = 0 OR GrpREf IS NULL) THEN Pro_ReqYarn2.Rate else Pro_ReqYarn2_Grp.Rate
 end ), 0) END AS Amount, 4 AS GrpSlno, Mas_Dept.DeptID,ISNULL(Pro_ReqYarn2.PrsLossPercet,0) as PrsLossPercent,0 As ColId FROM  Pro_ReqYarn INNER JOIN  Mas_Dept ON Pro_ReqYarn.DeptId = Mas_Dept.DeptID INNER JOIN  Pro_ReqYarn2 ON Pro_ReqYarn.OrdId =  Pro_ReqYarn2.OrdId AND Pro_ReqYarn.DeptId = Pro_ReqYarn2.DeptId AND Pro_ReqYarn.CountId = Pro_ReqYarn2.CountId AND Pro_ReqYarn.ColId = Pro_ReqYarn2.ColId INNER JOIN OrderMas ON Pro_ReqYarn.OrdId = OrderMas.OrdId LEFT  OUTER JOIN Pro_ReqYarn2 AS Pro_ReqYarn2_Grp ON Pro_ReqYarn.ColId = Pro_ReqYarn2_Grp.ColId AND  Pro_ReqYarn.CountId = Pro_ReqYarn2_Grp.CountId AND Pro_ReqYarn.DeptId = Pro_ReqYarn2_Grp.DeptId AND   OrderMas.grpref = Pro_ReqYarn2_Grp.OrdId GROUP BY Pro_ReqYarn.OrdId, Pro_ReqYarn.StyleNo,Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Dept.DeptID, OrderMas.grpref ,Manual_BudgetKGs_Entry,ISNULL(Pro_ReqYarn2.PrsLossPercet,0) 
 UNION ALL 
 SELECT Case When (GrpRef=0 or GrpREf Is NUll) then Pro_ReqKnitt.OrdID Else  GrpRef End as GrpOrdID,Pro_ReqKnitt.OrdId, Pro_ReqKnitt.Styleno,Mas_Dept.Deptname, Mas_Dept.OrderSno,CASE WHEN Mas_UOM_1.UOM='KGS' THEN ISNULL(SUM(Pro_ReqKnitt.ReqKgs * Case When (GrpRef=0 or GrpREf Is NUll) then   Pro_ReqKnitt2.Rate else  Pro_ReqKnitt2_Grp.Rate end  ), 0)  ELSE ISNULL(SUM(Pro_ReqKnitt.ReqMtr * Case When (GrpRef=0 or GrpREf Is NUll) then   Pro_ReqKnitt2.Rate else Pro_ReqKnitt2_Grp.Rate end  ), 0) END AS  Amount, 4 AS GrpSlno, Pro_ReqKnitt.DeptId,ISNULL(Pro_ReqKnitt2.PrsLossPercet,0) as  PrsLossPercent,0 As ColId FROM        Pro_ReqKnitt INNER JOIN OrderMas ON Pro_ReqKnitt.OrdId = OrderMas.OrdId INNER JOIN Mas_Dept ON Pro_ReqKnitt.DeptId = Mas_Dept.DeptID INNER JOIN Pro_ReqKnitt2 ON Pro_ReqKnitt.OrdId = Pro_ReqKnitt2.OrdId AND Pro_ReqKnitt.DeptId = Pro_ReqKnitt2.DeptId AND  Pro_ReqKnitt.FabId = Pro_ReqKnitt2.FabId AND Pro_ReqKnitt.ColId = Pro_ReqKnitt2.ColId AND  Pro_ReqKnitt.CntID = Pro_ReqKnitt2.CntID AND Pro_ReqKnitt.GSM = Pro_ReqKnitt2.GSM AND  Pro_ReqKnitt.GG = Pro_ReqKnitt2.GG AND Pro_ReqKnitt.LL = Pro_ReqKnitt2.LL AND  Pro_ReqKnitt.DiaID = Pro_ReqKnitt2.DiaID AND Isnull(Pro_ReqKnitt.DesignId,0) = Isnull(Pro_ReqKnitt2.DesignID,0) AND  Pro_ReqKnitt.FinDiaId = 
Pro_ReqKnitt2.FinDiaId AND Pro_ReqKnitt.FinGSM = Pro_ReqKnitt2.FinGSM INNER JOIN Mas_Fabric ON Pro_ReqKnitt.FabId = Mas_Fabric.FabID INNER JOIN Mas_Uom ON  Mas_Fabric.PriUomID = Mas_Uom.UomID LEFT OUTER JOIN Pro_ReqKnitt2 AS Pro_ReqKnitt2_Grp ON OrderMas.grpref = Pro_ReqKnitt2_Grp.OrdId AND Pro_ReqKnitt.DeptId = Pro_ReqKnitt2_Grp.DeptId AND        Pro_ReqKnitt.FabId = Pro_ReqKnitt2_Grp.FabId And Pro_ReqKnitt.ColId = Pro_ReqKnitt2_Grp.ColId And Pro_ReqKnitt.CntID = Pro_ReqKnitt2_Grp.CntID And Pro_ReqKnitt.GSM = Pro_ReqKnitt2_Grp.GSM And Pro_ReqKnitt.GG = Pro_ReqKnitt2_Grp.GG And Pro_ReqKnitt.LL  = Pro_ReqKnitt2_Grp.LL AND Pro_ReqKnitt.DiaID = Pro_ReqKnitt2_Grp.DiaID AND Isnull(Pro_ReqKnitt.DesignId,0) = Isnull(Pro_ReqKnitt2_Grp.DesignID,0) AND Pro_ReqKnitt.FinDiaId = Pro_ReqKnitt2_Grp.FinDiaId AND  Pro_ReqKnitt.FinGSM = Pro_ReqKnitt2_Grp.FinGSM LEFT OUTER JOIN Mas_Uom as Mas_UOM_1 ON Pro_ReqKnitt2.RateUOM = Mas_Uom_1.UomID  WHERE  ( Mas_Dept.DeptID <> 4  AND IsNull(Mas_Dept.DeptGrpCode,0) <> 4 )Group BY Pro_ReqKnitt.OrdId, Pro_ReqKnitt.Styleno,OrderMas.grpref, Mas_Dept.Deptname,  Mas_Dept.OrderSno ,mas_uom.uom, Pro_ReqKnitt.DeptId ,Mas_UOM_1.UOM,ISNULL(Pro_ReqKnitt2.PrsLossPercet,0)  
UNION ALL 
SELECT Case When (GrpRef=0 or  GrpREf Is NUll) then Pro_ReqKnitt.OrdID Else GrpRef End as GrpOrdID,Pro_ReqKnitt.OrdId, Pro_ReqKnitt.Styleno,Mas_Dept.Deptname,  Mas_Dept.OrderSno,CASE WHEN mas_uom.uom = 'kgs' THEN      ISNULL(SUM(Pro_ReqKnitt.ReqKgs * Case When (GrpRef=0 or GrpREf Is NUll) then   Pro_ReqKnitt2.Rate else Pro_ReqKnitt2_Grp.Rate end  ), 0) ELSE   ISNULL(SUM(Pro_ReqKnitt.Reqmtr * Case When (GrpRef=0  or GrpREf Is NUll) then   Pro_ReqKnitt2.Rate else Pro_ReqKnitt2_Grp.Rate end ), 0)   END AS Amount,  4 AS GrpSlno, Pro_ReqKnitt.DeptId,ISNULL(Pro_ReqKnitt2.PrsLossPercet,0) as PrsLossPercent,0 As ColId   FROM  Pro_ReqKnitt INNER JOIN OrderMas ON  Pro_ReqKnitt.OrdId = OrderMas.OrdId INNER JOIN Mas_Dept ON Pro_ReqKnitt.DeptId = Mas_Dept.DeptID INNER JOIN Pro_ReqKnitt2 ON Pro_ReqKnitt.OrdId = Pro_ReqKnitt2.OrdId AND Pro_ReqKnitt.DeptId = Pro_ReqKnitt2.DeptId AND  Pro_ReqKnitt.FabId = Pro_ReqKnitt2.FabId AND Pro_ReqKnitt.ColId = Pro_ReqKnitt2.ColId AND  Pro_ReqKnitt.CntID = Pro_ReqKnitt2.CntID AND Pro_ReqKnitt.GSM = Pro_ReqKnitt2.GSM AND  Pro_ReqKnitt.GG = Pro_ReqKnitt2.GG AND Pro_ReqKnitt.LL = Pro_ReqKnitt2.LL AND  Pro_ReqKnitt.DiaID = Pro_ReqKnitt2.DiaID AND  Pro_ReqKnitt.DesignId = Pro_ReqKnitt2.DesignID AND  Pro_ReqKnitt.FinDiaId = Pro_ReqKnitt2.FinDiaId AND Pro_ReqKnitt.FinGSM = Pro_ReqKnitt2.FinGSM INNER JOIN Mas_Fabric ON Pro_ReqKnitt.FabId = Mas_Fabric.FabID INNER JOIN    Mas_Uom ON Mas_Fabric.PriUomID  = Mas_Uom.UomID LEFT OUTER JOIN Pro_ReqKnitt2 AS Pro_ReqKnitt2_Grp ON OrderMas.grpref = Pro_ReqKnitt2_Grp.OrdId AND Pro_ReqKnitt.DeptId = Pro_ReqKnitt2_Grp.DeptId AND  Pro_ReqKnitt.FabId = Pro_ReqKnitt2_Grp.FabId AND    Pro_ReqKnitt.ColId = Pro_ReqKnitt2_Grp.ColId AND  Pro_ReqKnitt.CntID = Pro_ReqKnitt2_Grp.CntID AND Pro_ReqKnitt.GSM = Pro_ReqKnitt2_Grp.GSM AND  Pro_ReqKnitt.GG = Pro_ReqKnitt2_Grp.GG AND Pro_ReqKnitt.LL = Pro_ReqKnitt2_Grp.LL AND Pro_ReqKnitt.DiaID = Pro_ReqKnitt2_Grp.DiaID AND  Pro_ReqKnitt.DesignId = Pro_ReqKnitt2_Grp.DesignID AND Pro_ReqKnitt.FinDiaId = Pro_ReqKnitt2_Grp.FinDiaId AND  Pro_ReqKnitt.FinGSM = Pro_ReqKnitt2_Grp.FinGSM WHERE     (Mas_Dept.DeptID = 4 OR IsNull(Mas_Dept.DeptGrpCode,0) = 4 ) Group BY  Pro_ReqKnitt.OrdId, Pro_ReqKnitt.Styleno,OrderMas.grpref, Mas_Dept.Deptname, Mas_Dept.OrderSno,mas_uom.uom, Pro_ReqKnitt.DeptId,ISNULL(Pro_ReqKnitt2.PrsLossPercet,0) 
UNION ALL 
SELECT PRO_AccReq.OrdID as GrpOrdId,   PRO_AccReq.OrdID,PRO_AccReq.Styleno, 'ACCESSORIES' AS deptname, 100  AS slno, ISNULL(SUM(PRO_AccReq.ReqdQty   * (Pro_AccBudRate.BudRate )), 0) AS Amount,   3 AS GrpSlno, 16 AS DeptID,0 as PrsLossPercent,0 As ColId FROM         PRO_AccReq INNER JOIN  Pro_AccBudRate   ON PRO_AccReq.OrdID =  Pro_AccBudRate.OrdID AND PRO_AccReq.Acc_Type = Pro_AccBudRate.Acc_Type AND   PRO_AccReq.Acc_Desc =  Pro_AccBudRate.Acc_Desc AND PRO_AccReq.Clr = Pro_AccBudRate.Clr AND PRO_AccReq.Siz = Pro_AccBudRate.Siz   and PRO_AccReq.ItemType = Pro_AccBudRate.ItemType and PRO_AccReq.PrsID = Pro_AccBudRate.PrsID INNER JOIN OrderMas ON Pro_AccReq.OrdID = OrderMas.OrdID And Pro_AccBudRate.OrdID = OrderMas.OrdID WHERE PRO_AccReq.ItemType='M' And Pro_AccReq.PurchaseType='Purchase'   GROUP BY PRO_AccReq.OrdID ,PRO_AccReq.Styleno 
UNION  
SELECT PRO_AccReq.OrdID as GrpOrdId,   PRO_AccReq.OrdID,PRO_AccReq.Styleno,Mas_Dept.Deptname AS deptname, 100 AS slno, ISNULL(SUM(PRO_AccReq.ReqdQty   * Pro_AccBudRate.BudRate),0) AS Amount,   3 AS GrpSlno, 16 AS DeptID,0 as PrsLossPercent,0 As ColId FROM
 PRO_AccReq INNER JOIN  Pro_AccBudRate   ON PRO_AccReq.OrdID = Pro_AccBudRate.OrdID AND PRO_AccReq.Acc_Type = Pro_AccBudRate.Acc_Type AND   PRO_AccReq.Acc_Desc =   Pro_AccBudRate.Acc_Desc AND PRO_AccReq.Clr = Pro_AccBudRate.Clr AND 
PRO_AccReq.Siz = Pro_AccBudRate.Siz and PRO_AccReq.ItemType = Pro_AccBudRate.ItemType and PRO_AccReq.PrsID = Pro_AccBudRate.PrsID INNER JOIN OrderMas ON Pro_AccReq.OrdID = OrderMas.OrdID And Pro_AccBudRate.OrdID = OrderMas.OrdID INNER JOIN Mas_Dept ON PRO_AccReq.PrsID = Mas_Dept.DeptID WHERE PRO_AccReq.ItemType='S'   GROUP BY PRO_AccReq.OrdID,PRO_AccReq.Styleno,Mas_Dept.Deptname  
UNION ALL 
SELECT  Pro_ProdPros.OrdID as GrpOrdId, Pro_ProdPros.OrdID,Pro_ProdPros.STyleNo, Mas_Dept.Deptname, Mas_Dept.OrderSno
, ISNULL(SUM(Pro_ProdPros.Qty *   Pro_ProdPros.Rate), 0) AS Amount,   2 AS Grpslno, Mas_Dept.DeptID,0 as PrsLossPercent,0 As ColId FROM Pro_ProdPros INNER JOIN   Mas_Dept ON   Pro_ProdPros.ProdPros = Mas_Dept.DeptID INNER JOIN   OrderMas ON Pro_ProdPros.OrdID = OrderMas.OrdId INNER JOIN  Vue_OrdExcessQtyWitStyle ON Pro_ProdPros.OrdID = Vue_OrdExcessQtyWitStyle.OrdID AND   Pro_ProdPros.STyleNo =   Vue_OrdExcessQtyWitStyle.StyleNo  GROUP BY Pro_ProdPros.OrdID, Pro_ProdPros.STyleNo,Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Dept.DeptID  

UNION ALL 
/*Bit Dept Calculation */
SELECT   Trs_ProdExp.OrdID as GrpOrdID,  Trs_ProdExp.OrdId,Trs_ProdExp.StyleNo, Mas_JobWrkComp.WorkComplDet, Mas_Dept.OrderSno, 
CASE WHEN   ISNULL(Bud_InhRateclw.Rate_Pcs, 0)   > 0  THEN 
  case when isnull(Allow_excess_inbudget,'N')='Y' then Case When Mas_JobWrkComp.PcsType = 'Bit' And IsNull(Pro_ProdBitCutDet.PcsPerBit,1) > 0 Then (ISNULL(SUM(Vue_OrdExcessQtyWitStyleClr.ExsQty * Bud_InhRateclw.Rate_Pcs), 0) /  IsNull(Pro_ProdBitCutDet.PcsPerBit,1))  Else ISNULL(SUM(Vue_OrdExcessQtyWitStyleClr.ExsQty * Bud_InhRateclw.Rate_Pcs), 0) End
  else Case When Mas_JobWrkComp.PcsType = 'Bit' And IsNull(Pro_ProdBitCutDet.PcsPerBit,1) > 0 Then ( ISNULL(SUM(Vue_OrdExcessQtyWitStyleClr.orderQty * Bud_InhRateclw.Rate_Pcs), 0)/  IsNull(Pro_ProdBitCutDet.PcsPerBit,1) ) Else ISNULL(SUM(Vue_OrdExcessQtyWitStyleClr.orderQty * Bud_InhRateclw.Rate_Pcs), 0) End end
   ELSE 
   CASE WHEN   ISNULL(Bud_InhRateClw.JobWrkRate, 0)   > 0  THEN    case when isnull(Allow_excess_inbudget,'N') ='Y' then Case When Mas_JobWrkComp.PcsType = 'Bit' And IsNull(Pro_ProdBitCutDet.PcsPerBit,1) > 0 Then (ISNULL(SUM(Vue_OrdExcessQtyWitStyleClr.ExsQty * Bud_InhRateClw.JobWrkRate), 0)/  IsNull(Pro_ProdBitCutDet.PcsPerBit,1)) Else ISNULL(SUM(Vue_OrdExcessQtyWitStyleClr.ExsQty * Bud_InhRateClw.JobWrkRate), 0) End 
    else Case When Mas_JobWrkComp.PcsType = 'Bit' And IsNull(Pro_ProdBitCutDet.PcsPerBit,1) > 0 Then (ISNULL(SUM(Vue_OrdExcessQtyWitStyleClr.orderqty * Bud_InhRateClw.JobWrkRate), 0)/  IsNull(Pro_ProdBitCutDet.PcsPerBit,1) ) Else ISNULL(SUM(Vue_OrdExcessQtyWitStyleClr.orderqty * Bud_InhRateClw.JobWrkRate), 0)  End End
	  ELSE 
	  CASE WHEN   ISNULL(Pro_Prod_PartwiseRate.Rate, 0)   > 0  THEN   case  when isnull(Allow_excess_inbudget,'N')='Y'  then Case When Mas_JobWrkComp.PcsType = 'Bit' And IsNull(Pro_ProdBitCutDet.PcsPerBit,1) > 0 Then ( ISNULL(SUM(Vue_OrdExcessQtyWitStyleClr.ExsQty * Pro_Prod_PartwiseRate.Rate), 0)/  IsNull(Pro_ProdBitCutDet.PcsPerBit,1)) Else ISNULL(SUM(Vue_OrdExcessQtyWitStyleClr.ExsQty * Pro_Prod_PartwiseRate.Rate), 0) End
	   else  Case When Mas_JobWrkComp.PcsType = 'Bit' And IsNull(Pro_ProdBitCutDet.PcsPerBit,1) > 0 Then (ISNULL(SUM(Vue_OrdExcessQtyWitStyleClr.orderqty * Pro_Prod_PartwiseRate.Rate), 0) /  IsNull(Pro_ProdBitCutDet.PcsPerBit,1)) Else ISNULL(SUM(Vue_OrdExcessQtyWitStyleClr.orderqty * Pro_Prod_PartwiseRate.Rate), 0)  end End

	  ELSE CASE WHEN    ISNULL(Pro_Prod_PartwiseRate.JobWrkRate, 0)   > 0  THEN   case when isnull(Allow_excess_inbudget,'N')='Y' then Case When Mas_JobWrkComp.PcsType = 'Bit' And IsNull(Pro_ProdBitCutDet.PcsPerBit,1) > 0 Then ( ISNULL(SUM(Vue_OrdExcessQtyWitStyleClr.ExsQty * Pro_Prod_PartwiseRate.JobWrkRate), 0)/  IsNull(Pro_ProdBitCutDet.PcsPerBit,1) ) Else ISNULL(SUM(Vue_OrdExcessQtyWitStyleClr.ExsQty * Pro_Prod_PartwiseRate.JobWrkRate), 0) End 
	  else  Case When Mas_JobWrkComp.PcsType = 'Bit' And IsNull(Pro_ProdBitCutDet.PcsPerBit,1) > 0 Then (ISNULL(SUM(Vue_OrdExcessQtyWitStyleClr.orderqty * Pro_Prod_PartwiseRate.JobWrkRate), 0)/  IsNull(Pro_ProdBitCutDet.PcsPerBit,1)  ) Else ISNULL(SUM(Vue_OrdExcessQtyWitStyleClr.orderqty * Pro_Prod_PartwiseRate.JobWrkRate), 0)  End End
	  Else 0 
	  End END End End AS Amount   , 2 AS Grpslno, Mas_Dept.DeptID,0 as PrsLossPercent,Vue_OrdExcessQtyWitStyleClr.ColId FROM   Trs_ProdExp INNER JOIN  Mas_Dept INNER JOIN Mas_JobWrkComp ON Mas_Dept.DeptID = Mas_JobWrkComp.DeptId ON   Trs_ProdExp.WrkID = Mas_JobWrkComp.Id INNER JOIN   OrderMas ON Trs_ProdExp.OrdId = OrderMas.OrdId INNER JOIN Vue_OrdExcessQtyWitStyleClr ON Trs_ProdExp.OrdId = Vue_OrdExcessQtyWitStyleClr.OrdID AND Trs_ProdExp.StyleNo = Vue_OrdExcessQtyWitStyleClr.StyleNo LEFT OUTER JOIN (Select Distinct OrdId,StyleNo,PartId,ClrId,JobWrkRate,NWork,Rate_Pcs From Bud_InhRateclw)  Bud_InhRateclw ON  Trs_ProdExp.OrdId = Bud_InhRateclw.OrdID  And /* 'Nasima Vue_OrdExcessQtyWitStyleClr.ColId =   Bud_InhRateclw.ClrID */ (1=Case When (Select IsNull(BudRt_CMT_Sizewise,'N') From Options)='N' and Bud_InhRateclw.ClrID=Vue_OrdExcessQtyWitStyleClr.ColId Then 0 Else 1 End) AND  Trs_ProdExp.StyleNo = Bud_InhRateclw.Styleno AND   Trs_ProdExp.WrkID = Bud_InhRateclw.NWork and Vue_OrdExcessQtyWitStyleClr.PartId = Bud_InhRateclw.PartId  LEFT OUTER JOIN Pro_Prod_PartwiseRate ON Trs_ProdExp.OrdId=Pro_Prod_PartwiseRate.OrdId And Trs_ProdExp.StyleNo=Pro_Prod_PartwiseRate.StyleNo And Trs_ProdExp.WrkID=Pro_Prod_PartwiseRate.WrkID And  Vue_OrdExcessQtyWitStyleClr.PartId=Pro_Prod_PartwiseRate.PartID LEFT OUTER JOIN ( Select Distinct Ordid, Styleno,WrkId, PcsPerBit From Pro_ProdBitCutDet)  As Pro_ProdBitCutDet On Pro_ProdBitCutDet.Ordid = Trs_ProdExp.OrdId And Trs_ProdExp.StyleNo = Pro_ProdBitCutDet.Styleno  cross join options  Where Mas_Dept.SEMIFINISH='S' And IsNull(Mas_JobWrkComp.ProdType,'C')='C' GROUP BY Trs_ProdExp.OrdId, Trs_ProdExp.StyleNo,Mas_JobWrkComp.WorkComplDet, Mas_Dept.OrderSno,    Mas_Dept.DeptID, ISNULL(Bud_InhRateclw.Rate_Pcs, 0),isnull(Allow_excess_inbudget,'N'),IsNull(Pro_Prod_PartwiseRate.Rate,0),IsNull(Pro_Prod_PartwiseRate.JobWrkRate,0),IsNull(Trs_ProdExp.Rate,0),Vue_OrdExcessQtyWitStyleClr.ColId ,Bud_InhRateclw.JobWrkRate,Isnull(Pro_ProdBitCutDet.PcsPerBit,1) , Mas_JobWrkComp.PcsType   
UNION ALL     
SELECT Trs_ProdExp.OrdID as GrpOrdID,  Trs_ProdExp.OrdId, Trs_ProdExp.StyleNo,Mas_JobWrkComp.WorkComplDet, Mas_Dept.OrderSno,    CASE WHEN   ISNULL(Bud_InhRateclw.Rate_Pcs, 0)   > 0  THEN   case when isnull(Allow_excess_inbudget,'N')='Y' then  ISNULL(SUM(Vue_OrdExcessQtyWitStyleClr.ExsQty * Bud_InhRateclw.Rate_Pcs), 0) else ISNULL(SUM(Vue_OrdExcessQtyWitStyleClr.orderQty * Bud_InhRateclw.Rate_Pcs), 0) end     ELSE CASE WHEN   ISNULL(Bud_InhRateClw.JobWrkRate, 0)   > 0  THEN   case when   isnull(Allow_excess_inbudget,'N')='Y' then ISNULL(SUM(Vue_OrdExcessQtyWitStyleClr.ExsQty * Bud_InhRateClw.JobWrkRate), 0) else ISNULL(SUM(Vue_OrdExcessQtyWitStyleClr.orderqty * Bud_InhRateClw.JobWrkRate), 0)  End ELSE CASE WHEN   ISNULL(Pro_Prod_PartwiseRate.Rate, 0)   > 0  THEN   case when isnull(Allow_excess_inbudget,'N')='Y' then ISNULL(SUM(Vue_OrdExcessQtyWitStyleClr.ExsQty * Pro_Prod_PartwiseRate.Rate), 0) else ISNULL(SUM(Vue_OrdExcessQtyWitStyleClr.orderqty *
 Pro_Prod_PartwiseRate.Rate), 0)  end ELSE CASE WHEN   ISNULL(Pro_Prod_PartwiseRate.JobWrkRate, 0)   > 0  THEN   case when isnull(Allow_excess_inbudget,'N')='Y' then ISNULL(SUM(Vue_OrdExcessQtyWitStyleClr.ExsQty * Pro_Prod_PartwiseRate.JobWrkRate), 0) else ISNULL  (SUM(Vue_OrdExcessQtyWitStyleClr.orderqty * Pro_Prod_PartwiseRate.JobWrkRate), 0)  End Else 0 End End END End AS Amount  , 1 AS Grpslno, Mas_Dept.DeptID,0 as PrsLossPercent,Vue_OrdExcessQtyWitStyleClr.ColId FROM         Trs_ProdExp INNER JOIN  Mas_Dept INNER JOIN Mas_JobWrkComp ON Mas_Dept.DeptID =  Mas_JobWrkComp.DeptId ON   Trs_ProdExp.WrkID = Mas_JobWrkComp.Id INNER JOIN   OrderMas ON Trs_ProdExp.OrdId = OrderMas.OrdId INNER JOIN    Vue_OrdExcessQtyWitStyleClr ON Trs_ProdExp.OrdId = Vue_OrdExcessQtyWitStyleClr.OrdID AND Trs_ProdExp.StyleNo =   Vue_OrdExcessQtyWitStyleClr.StyleNo LEFT OUTER JOIN (Select Distinct OrdId,Styleno,PartID,ClrID,Rate_Pcs,JobWrkRate,NWork From Bud_InhRateclw)  Bud_InhRateclw ON Trs_ProdExp.OrdId = Bud_InhRateclw.OrdID
 AND  Trs_ProdExp.StyleNo = Bud_InhRateclw.Styleno AND   Trs_ProdExp.WrkID = Bud_InhRateclw.NWork  and Vue_OrdExcessQtyWitStyleClr.PartId = Bud_InhRateclw.PartId and /* 'Nasima Vue_OrdExcessQtyWitStyleClr.ColId =   Bud_InhRateclw.ClrID*/ (1=Case When (Select IsNull(BudRt_CMT_Sizewise,'N') From Options)='N' and Vue_OrdExcessQtyWitStyleClr.ColId=Bud_InhRateclw.ClrID Then 0 Else 1 End) LEFT OUTER JOIN Pro_Prod_PartwiseRate ON Trs_ProdExp.OrdId=Pro_Prod_PartwiseRate.OrdId And Trs_ProdExp.StyleNo=Pro_Prod_PartwiseRate.StyleNo And Trs_ProdExp.WrkID=Pro_Prod_PartwiseRate.WrkID And Vue_OrdExcessQtyWitStyleClr.PartId=Pro_Prod_PartwiseRate.PartID cross join options  Where Mas_Dept.SEMIFINISH='S' And Pro_Prod_PartwiseRate.PartID Is Not Null And IsNull(Mas_JobWrkComp.ProdType,'C')='A' GROUP BY Trs_ProdExp.OrdId, Trs_ProdExp.StyleNo,Mas_JobWrkComp.WorkComplDet, Mas_Dept.OrderSno,   Mas_Dept.DeptID, ISNULL(Bud_InhRateclw.Rate_Pcs, 0),isnull(Allow_excess_inbudget,'N'),IsNull(Pro_Prod_PartwiseRate.Rate,0),IsNull(Pro_Prod_PartwiseRate.JobWrkRate,0),IsNull(Trs_ProdExp.Rate,0),Vue_OrdExcessQtyWitStyleClr.ColId,Bud_InhRateClw.JobWrkRate 
  UNION ALL 
  SELECT X.GrpOrdID,X.OrdId,X.StyleNo,X.WorkComplDet,X.OrderSno,IsNull(Sum(X.Amount),0) As Amount, X.Grpslno,X.DeptID,X.PrsLossPercent,X.ColId From (SELECT Distinct Trs_ProdExp.OrdID as GrpOrdID,  Trs_ProdExp.OrdId,Trs_ProdExp.StyleNo, Mas_JobWrkComp.WorkComplDet, Mas_Dept.OrderSno,CASE WHEN   ISNULL(Bud_InhRateclw.Rate_Pcs, 0)   >0  THEN   case when isnull(Allow_excess_inbudget,'N')=
'Y' then ISNULL((Vue_OrdExcessQtyWitStyleClr.ExsQty * Bud_InhRateclw.Rate_Pcs), 0) else ISNULL((Vue_OrdExcessQtyWitStyleClr.orderQty * Bud_InhRateclw.Rate_Pcs), 0) end ELSE CASE WHEN  ISNULL(Bud_InhRateClw.JobWrkRate, 0)   > 0  THEN   case when isnull(Allow_excess_inbudget,'N')='Y' then ISNULL((Vue_OrdExcessQtyWitStyleClr.ExsQty * Bud_InhRateClw.JobWrkRate), 0) else ISNULL((Vue_OrdExcessQtyWitStyleClr.orderqty * Bud_InhRateClw.JobWrkRate), 0)  end ELSE CASE WHEN   ISNULL(Pro_Prod_PartwiseRate.Rate, 0)   >
 0  THEN   case when isnull(Allow_excess_inbudget,'N')='Y' then ISNULL((Vue_OrdExcessQtyWitStyleClr.ExsQty * Pro_Prod_PartwiseRate.Rate), 0) else ISNULL((Vue_OrdExcessQtyWitStyleClr.orderqty * Pro_Prod_PartwiseRate.Rate), 0)  end ELSE CASE WHEN  ISNULL(Pro_Prod_PartwiseRate.JobWrkRate, 0)   > 0  THEN   case when isnull(Allow_excess_inbudget,'N')='Y' then ISNULL((Vue_OrdExcessQtyWitStyleClr.ExsQty * Pro_Prod_PartwiseRate.JobWrkRate), 0) else ISNULL((Vue_OrdExcessQtyWitStyleClr.orderqty * Pro_Prod_PartwiseRate.JobWrkRate), 0)  end ELSE CASE WHEN   ISNULL(Trs_ProdExp.Rate, 0)   > 0  THEN case when isnull(Allow_excess_inbudget,'N')='Y' then ISNULL((Vue_OrdExcessQtyWitStyleClr.ExsQty * Trs_ProdExp.Rate), 0) else ISNULL((Vue_OrdExcessQtyWitStyleClr.orderqty * Trs_ProdExp.Rate), 0) End ELSE case when isnull(Allow_excess_inbudget,'N')='Y' then ISNULL((Vue_OrdExcessQtyWitStyleClr.ExsQty * Trs_ProdExp.JobWrkRate), 0) else ISNULL((Vue_OrdExcessQtyWitStyleClr.orderqty * Trs_ProdExp.JobWrkRate), 0) End end End END End End AS Amount ,2 AS Grpslno,  Mas_Dept.DeptID,0 as PrsLossPercent,Vue_OrdExcessQtyWitStyleClr.ColId FROM  Trs_ProdExp INNER JOIN  Mas_Dept INNER JOIN Mas_JobWrkComp ON Mas_Dept.DeptID = Mas_JobWrkComp.DeptId ON   Trs_ProdExp.WrkID = Mas_JobWrkComp.Id INNER JOIN   OrderMas ON Trs_ProdExp.OrdId = OrderMas.OrdId INNER JOIN     Vue_OrdExcessQtyWitStyleClr ON Trs_ProdExp.OrdId = Vue_OrdExcessQtyWitStyleClr.OrdID AND     Trs_ProdExp.StyleNo =   Vue_OrdExcessQtyWitStyleClr.StyleNo LEFT OUTER JOIN (Select Distinct OrdID,Styleno,PartID,ClrID,Rate_Pcs,JobWrkRate,NWork From Bud_InhRateclw)  Bud_InhRateclw ON Trs_ProdExp.OrdId = Bud_InhRateclw.OrdID AND  Trs_ProdExp.StyleNo = Bud_InhRateclw.Styleno AND   Trs_ProdExp.WrkID = Bud_InhRateclw.NWork and Vue_OrdExcessQtyWitStyleClr.PartId = Bud_InhRateclw.PartId And /* 'Nasima ' Vue_OrdExcessQtyWitStyleClr.ColId =   Bud_InhRateclw.ClrID */ (1=Case When (Select IsNull(BudRt_CMT_Sizewise,'N') From Options)='N' and Vue_OrdExcessQtyWitStyleClr.ColId=Bud_InhRateclw.ClrID Then 0 Else 1 End) LEFT OUTER JOIN Pro_Prod_PartwiseRate ON Trs_ProdExp.OrdId=Pro_Prod_PartwiseRate.OrdId And Trs_ProdExp.StyleNo=Pro_Prod_PartwiseRate.StyleNo And Trs_ProdExp.WrkID=Pro_Prod_PartwiseRate.WrkID cross join options  Where Mas_Dept.SEMIFINISH='F' 
And IsNull(Pro_Prod_PartwiseRate.PartId,0)<>0 And IsNull(Mas_JobWrkComp.ProdType,'C')='C') X GROUP BY X.GrpOrdID,X.OrdId, X.StyleNo,X.WorkComplDet, X.OrderSno,X.Grpslno,X.DeptID,X.PrsLossPercent,X.ColId    
UNION ALL 
SELECT X.GrpOrdID,X.OrdId,X.StyleNo,X.WorkComplDet,X.OrderSno,IsNull(Sum(X.Amount),0) As Amount, X.Grpslno,X.DeptID,X.PrsLossPercent,X.ColId From (SELECT Distinct Trs_ProdExp.OrdID as GrpOrdID,  Trs_ProdExp.OrdId, Trs_ProdExp.StyleNo,Mas_JobWrkComp.WorkComplDet, Mas_Dept.OrderSno,CASE WHEN   ISNULL(Bud_InhRateclw.Rate_Pcs, 0)   > 0  THEN   case when  isnull(Allow_excess_inbudget,'N')='Y' then ISNULL((Vue_OrdExcessQtyWitStyleClr.ExsQty * Bud_InhRateclw.Rate_Pcs), 0) else ISNULL((Vue_OrdExcessQtyWitStyleClr.orderQty * Bud_InhRateclw.Rate_Pcs), 0) end ELSE CASE WHEN   ISNULL(Bud_InhRateclw.JobWrkRate, 0)   > 0  THEN   case when isnull(Allow_excess_inbudget,'N')='Y' then ISNULL((Vue_OrdExcessQtyWitStyleClr.ExsQty * Bud_InhRateclw.JobWrkRate), 0) else ISNULL((Vue_OrdExcessQtyWitStyleClr.orderqty * 
Bud_InhRateclw.JobWrkRate), 0)  end ELSE CASE WHEN   ISNULL(Pro_Prod_PartwiseRate.Rate, 0)   > 0  THEN   case when isnull(Allow_excess_inbudget,'N')='Y' then ISNULL((Vue_OrdExcessQtyWitStyleClr.ExsQty * Pro_Prod_PartwiseRate.Rate), 0) else ISNULL((Vue_OrdExcessQtyWitStyleClr.orderqty * Pro_Prod_PartwiseRate.Rate), 0)  end ELSE CASE WHEN   ISNULL(Pro_Prod_PartwiseRate.JobWrkRate, 0)   > 0  THEN   case when isnull(Allow_excess_inbudget,'N')='Y' then ISNULL((Vue_OrdExcessQtyWitStyleClr.ExsQty * Pro_Prod_PartwiseRate.JobWrkRate), 0) else ISNULL((Vue_OrdExcessQtyWitStyleClr.orderqty * Pro_Prod_PartwiseRate.JobWrkRate), 0)  end ELSE CASE WHEN   ISNULL(Trs_ProdExp.Rate, 0)   > 0  THEN case when isnull(Allow_excess_inbudget,'N')='Y' then ISNULL((Vue_OrdExcessQtyWitStyleClr.ExsQty * Trs_ProdExp.Rate), 0) else  ISNULL((Vue_OrdExcessQtyWitStyleClr.orderqty * Trs_ProdExp.Rate), 0) End ELSE case when isnull(Allow_excess_inbudget,'N')='Y' then ISNULL((Vue_OrdExcessQtyWitStyleClr.ExsQty * Trs_ProdExp.JobWrkRate), 0) else ISNULL((Vue_OrdExcessQtyWitStyleClr.orderqty *  Trs_ProdExp.JobWrkRate), 0) End end End END End End AS Amount  , 1 AS Grpslno, Mas_Dept.DeptID,0 as PrsLossPercent,Vue_OrdExcessQtyWitStyleClr.ColId FROM Trs_ProdExp INNER JOIN  Mas_Dept INNER JOIN Mas_JobWrkComp ON Mas_Dept.DeptID =  Mas_JobWrkComp.DeptId ON   Trs_ProdExp.WrkID = Mas_JobWrkComp.Id INNER JOIN   OrderMas ON Trs_ProdExp.OrdId = OrderMas.OrdId INNER JOIN     Vue_OrdExcessQtyWitStyleClr ON Trs_ProdExp.OrdId = Vue_OrdExcessQtyWitStyleClr.OrdID 
AND     Trs_ProdExp.StyleNo =    Vue_OrdExcessQtyWitStyleClr.StyleNo LEFT OUTER JOIN (Select Distinct OrdID,Styleno,PartID,NWork,ClrID,JobWrkRate,Rate_Pcs From Bud_InhRateclw)   Bud_InhRateclw ON  Trs_ProdExp.OrdId = Bud_InhRateclw.OrdID AND  Trs_ProdExp.StyleNo = Bud_InhRateclw.Styleno AND   Trs_ProdExp.WrkID =  Bud_InhRateclw.NWork and Vue_OrdExcessQtyWitStyleClr.PartId = Bud_InhRateclw.PartId  And  /* 'Nasima Vue_OrdExcessQtyWitStyleClr.ColId =   Bud_InhRateclw.ClrID */ (1=Case When (Select IsNull(BudRt_CMT_Sizewise,'N') From Options)='N' and  Vue_OrdExcessQtyWitStyleClr.ColId=Bud_InhRateclw.ClrID Then 0 Else 1 End) LEFT OUTER JOIN Pro_Prod_PartwiseRate ON Trs_ProdExp.OrdId=Pro_Prod_PartwiseRate.OrdId And Trs_ProdExp.StyleNo=Pro_Prod_PartwiseRate.StyleNo And Trs_ProdExp.WrkID= Pro_Prod_PartwiseRate.WrkID cross join options  Where Mas_Dept.SEMIFINISH='F' And IsNull(Pro_Prod_PartwiseRate.PartId,0)<>0 And IsNull(Mas_JobWrkComp.ProdType,'C')='A') X GROUP BY X.GrpOrdID,X.OrdId, x.StyleNo,X.WorkComplDet, X.OrderSno,X.Grpslno,X.DeptID, X.PrsLossPercent,X.ColId 
UNION ALL  
SELECT X.GrpOrdID,X.OrdId,X.StyleNo,X.WorkComplDet,X.OrderSno,IsNull(Sum(X.Amount),0) As Amount, X.Grpslno,X.DeptID,X.PrsLossPercent,X.ColId From (SELECT  Trs_ProdExp.StyleNo, Trs_ProdExp.OrdID as GrpOrdID,  Trs_ProdExp.OrdId,  Mas_JobWrkComp.WorkComplDet, Mas_Dept.OrderSno, CASE WHEN   ISNULL(Bud_InhRateclw.Rate_Pcs, 0)   > 0  THEN   case when isnull(Allow_excess_inbudget,'N')='Y' then ISNULL(((Vue_OrdExcessQtyWitStyleClr1.ExsQty/PcePerPack)
 * Bud_InhRateclw.Rate_Pcs), 0) else ISNULL(((Vue_OrdExcessQtyWitStyleClr1.orderQty/PcePerPack) * Bud_InhRateclw.Rate_Pcs), 0) end ELSE CASE WHEN   ISNULL(Bud_InhRateclw.JobWrkRate, 0)   > 0  THEN   case when isnull(Allow_excess_inbudget,'N')='Y' then ISNULL(((Vue_OrdExcessQtyWitStyleClr1.ExsQty/PcePerPack) *  Bud_InhRateclw.JobWrkRate), 0) else ISNULL(((Vue_OrdExcessQtyWitStyleClr1.orderqty/PcePerPack) * Bud_InhRateclw.JobWrkRate), 0)  end ELSE CASE WHEN   ISNULL(Pro_Prod_PartwiseRate.Rate, 0)   > 0  THEN   case when isnull (Allow_excess_inbudget,'N')='Y' then ISNULL(((Vue_OrdExcessQtyWitStyleClr.ExsQty/PcePerPack) * Pro_Prod_PartwiseRate.Rate), 0) else ISNULL(((Vue_OrdExcessQtyWitStyleClr.orderqty/PcePerPack) * Pro_Prod_PartwiseRate.Rate), 0)  end ELSE 
 CASE WHEN   ISNULL(Pro_Prod_PartwiseRate.JobWrkRate, 0)   > 0  THEN   case when isnull(Allow_excess_inbudget,'N')='Y' then ISNULL(((Vue_OrdExcessQtyWitStyleClr.ExsQty/PcePerPack) * Pro_Prod_PartwiseRate.JobWrkRate), 0) else ISNULL(((Vue_OrdExcessQtyWitStyleClr.orderqty/PcePerPack) * Pro_Prod_PartwiseRate.JobWrkRate), 0)  end ELSE CASE WHEN   ISNULL(Trs_ProdExp.Rate, 0)   > 0  THEN case when isnull(Allow_excess_inbudget,'N')='Y' then ISNULL(((Vue_OrdExcessQtyWitStyleClr.ExsQty/PcePerPack) * Trs_ProdExp.Rate), 0) else  ISNULL(((Vue_OrdExcessQtyWitStyleClr.orderqty/PcePerPack) * Trs_ProdExp.Rate), 0) End ELSE case when isnull(Allow_excess_inbudget,'N')='Y' then ISNULL(((Vue_OrdExcessQtyWitStyleClr.ExsQty/PcePerPack) * Trs_ProdExp.JobWrkRate), 0) else ISNULL(((Vue_OrdExcessQtyWitStyleClr.orderqty/PcePerPack) * Trs_ProdExp.JobWrkRate), 0) End end End END End End AS Amount  ,2 AS Grpslno, Mas_Dept.DeptID,0 as PrsLossPercent,IsNull(Vue_OrdExcessQtyWitStyleClr1.ColId,0) As ColId,Pro_Prod_PartwiseRate.PartID    FROM Trs_ProdExp INNER JOIN  Mas_Dept INNER JOIN Mas_JobWrkComp ON Mas_Dept.DeptID = Mas_JobWrkComp.DeptId ON   Trs_ProdExp.WrkID = Mas_JobWrkComp.Id /*''Nasi'' PcePerPack Taken From OrderStyleDtl'' INNER JOIN   OrderMas ON Trs_ProdExp.OrdId = OrderMas.OrdId */ INNER JOIN OrderStyleDtl ON OrderStyleDtl.OrdId=Trs_ProdExp.OrdId and OrderStyleDtl.StyleNo=Trs_ProdExp.StyleNo   INNER JOIN Vue_OrdExcessQtyWitStyle_WithoutClr As Vue_OrdExcessQtyWitStyleClr ON Trs_ProdExp.OrdId = Vue_OrdExcessQtyWitStyleClr.OrdID AND     Trs_ProdExp.StyleNo =   Vue_OrdExcessQtyWitStyleClr.StyleNo LEFT OUTER JOIN (Select Distinct OrdID,Styleno,PartID,NWork,ClrID,JobWrkRate,Rate_Pcs From Bud_InhRateclw)  Bud_InhRateclw ON Trs_ProdExp.OrdId = Bud_InhRateclw.OrdID AND  Trs_ProdExp.StyleNo = Bud_InhRateclw.Styleno AND   Trs_ProdExp.WrkID = Bud_InhRateclw.NWork LEFT OUTER JOIN Vue_OrdExcessQtyWitStyleClrNew As Vue_OrdExcessQtyWitStyleClr1 ON Trs_ProdExp.OrdId = Vue_OrdExcessQtyWitStyleClr1.OrdID AND Trs_ProdExp.StyleNo =   Vue_OrdExcessQtyWitStyleClr1.StyleNo And /* 'Nasima ' Bud_InhRateclw.ClrID = Vue_OrdExcessQtyWitStyleClr1.ColId */  (1=Case When (Select IsNull(BudRt_CMT_Sizewise,'N') From Options)='N' and Bud_InhRateclw.ClrID = Vue_OrdExcessQtyWitStyleClr1.ColId Then 0 Else 1 End) AND Vue_OrdExcessQtyWitStyleClr1.Partid=Vue_OrdExcessQtyWitStyleClr.PartId LEFT OUTER JOIN Pro_Prod_PartwiseRate ON Trs_ProdExp.OrdId=Pro_Prod_PartwiseRate.OrdId And Trs_ProdExp.StyleNo=Pro_Prod_PartwiseRate.StyleNo And Trs_ProdExp.WrkID=Pro_Prod_PartwiseRate.WrkID cross join options Where Mas_Dept.SEMIFINISH='F' And    IsNull(Pro_Prod_PartwiseRate.PartId,0)=0 And IsNull(Mas_JobWrkComp.ProdType,'C')='C') X GROUP BY X.GrpOrdID,X.OrdId,x.StyleNo, X.WorkComplDet, X.OrderSno,X.Grpslno,X.DeptID,X.PrsLossPercent,
  X.ColId   
  UNION ALL    
SELECT X.GrpOrdID,X.OrdId,X.StyleNo,X.WorkComplDet,X.OrderSno,IsNull(Sum(X.Amount),0) As Amount, X.Grpslno,X.DeptID,X.PrsLossPercent,X.ColId From (SELECT  Trs_ProdExp.StyleNo, Trs_ProdExp.OrdID as GrpOrdID,  Trs_ProdExp.OrdId, Mas_JobWrkComp.WorkComplDet, Mas_Dept.OrderSno, CASE WHEN   ISNULL(Bud_InhRateclw.Rate_Pcs, 0)   > 0  THEN   case when isnull(Allow_excess_inbudget,'N')='Y' then ISNULL(((Vue_OrdExcessQtyWitStyleClr1.ExsQty/PcePerPack) * Bud_InhRateclw.Rate_Pcs), 0) else ISNULL(((Vue_OrdExcessQtyWitStyleClr1.orderQty/PcePerPack) * Bud_InhRateclw.Rate_Pcs), 0) end ELSE CASE WHEN   ISNULL(Bud_InhRateclw.JobWrkRate, 0)   > 0  THEN   case when isnull(Allow_excess_inbudget,'N')='Y' then ISNULL(((Vue_OrdExcessQtyWitStyleClr1.ExsQty/PcePerPack) * Bud_InhRateclw.JobWrkRate), 0) else ISNULL(((Vue_OrdExcessQtyWitStyleClr1.orderqty /PcePerPack) * Bud_InhRateclw.JobWrkRate), 0)  end ELSE CASE WHEN   ISNULL(Pro_Prod_PartwiseRate.Rate, 0)   > 0  THEN   case when isnull(Allow_excess_inbudget,'N')='Y' then ISNULL((
(Vue_OrdExcessQtyWitStyleClr.ExsQty/PcePerPack) * Pro_Prod_PartwiseRate.Rate), 0) else ISNULL(((Vue_OrdExcessQtyWitStyleClr.orderqty/PcePerPack) * Pro_Prod_PartwiseRate.Rate),0)  end ELSE CASE WHEN   ISNULL(Pro_Prod_PartwiseRate.JobWrkRate, 0)   > 0  THEN   case when isnull(Allow_excess_inbudget,'N')='Y' then ISNULL(((Vue_OrdExcessQtyWitStyleClr.ExsQty/PcePerPack) * Pro_Prod_PartwiseRate.JobWrkRate), 0) else ISNULL(((Vue_OrdExcessQtyWitStyleClr.orderqty/PcePerPack) * Pro_Prod_PartwiseRate.JobWrkRate), 0)  end ELSE CASE WHEN   ISNULL(Trs_ProdExp.Rate, 0)   > 0  THEN case when isnull(Allow_excess_inbudget,'N')='Y' then ISNULL(((Vue_OrdExcessQtyWitStyleClr.ExsQty/PcePerPack) * Trs_ProdExp.Rate), 0) else ISNULL(((Vue_OrdExcessQtyWitStyleClr.orderqty/PcePerPack) * Trs_ProdExp.Rate), 0) End ELSE case when isnull(Allow_excess_inbudget,'N')='Y' then ISNULL(((Vue_OrdExcessQtyWitStyleClr.ExsQty/PcePerPack) * Trs_ProdExp.JobWrkRate), 0) else ISNULL(((Vue_OrdExcessQtyWitStyleClr.orderqty/PcePerPack) * Trs_ProdExp.JobWrkRate), 0) End end End END End End AS Amount  ,1 AS Grpslno, Mas_Dept.DeptID,0 as  PrsLossPercent,IsNull(Vue_OrdExcessQtyWitStyleClr1.ColId,0) As ColId,Pro_Prod_PartwiseRate.PartID FROM Trs_ProdExp INNER JOIN  Mas_Dept INNER JOIN Mas_JobWrkComp ON Mas_Dept.DeptID = Mas_JobWrkComp.DeptId ON   Trs_ProdExp.WrkID = Mas_JobWrkComp.Id /*''Nasi''PcePerPack Taken From OrderStyleDtl ''INNER JOIN   OrderMas ON Trs_ProdExp.OrdId = OrderMas.OrdId*/ INNER JOIN OrderStyleDtl ON OrderStyleDtl.OrdId=Trs_ProdExp.OrdId and OrderStyleDtl.StyleNo=Trs_ProdExp.StyleNo INNER JOIN Vue_OrdExcessQtyWitStyle_WithoutClr As Vue_OrdExcessQtyWitStyleClr ON Trs_ProdExp.OrdId = Vue_OrdExcessQtyWitStyleClr.OrdID AND     Trs_ProdExp.StyleNo =   Vue_OrdExcessQtyWitStyleClr.StyleNo LEFT OUTER JOIN (Select Distinct OrdID,Styleno,PartID,NWork,ClrID,Rate_Pcs,JobWrkRate From Bud_InhRateclw)  Bud_InhRateclw ON Trs_ProdExp.OrdId = Bud_InhRateclw.OrdID AND  Trs_ProdExp.StyleNo = Bud_InhRateclw.Styleno AND   Trs_ProdExp.WrkID = Bud_InhRateclw.NWork LEFT OUTER JOIN Vue_OrdExcessQtyWitStyleClrNew As Vue_OrdExcessQtyWitStyleClr1 ON Trs_ProdExp.OrdId = Vue_OrdExcessQtyWitStyleClr1.OrdID AND Trs_ProdExp.StyleNo =   Vue_OrdExcessQtyWitStyleClr1.StyleNo and /* 'Nasima 'Bud_InhRateclw.ClrID = Vue_OrdExcessQtyWitStyleClr1.ColId*/ (1=Case When (Select IsNull(BudRt_CMT_Sizewise,'N') From Options)='N' and Bud_InhRateclw.ClrID = Vue_OrdExcessQtyWitStyleClr1.ColId Then 0 Else 1 End) LEFT OUTER JOIN Pro_Prod_PartwiseRate ON Trs_ProdExp.OrdId=Pro_Prod_PartwiseRate.OrdId And Trs_ProdExp.StyleNo=Pro_Prod_PartwiseRate.StyleNo And Trs_ProdExp.WrkID=Pro_Prod_PartwiseRate.WrkID cross join options Where Mas_Dept.SEMIFINISH='F' And IsNull(Pro_Prod_PartwiseRate.PartId,0)=0 And IsNull(Mas_JobWrkComp.ProdType,'C')='A') X GROUP BY X.GrpOrdID,X.OrdId,X.StyleNo, X.WorkComplDet, X.OrderSno,X.Grpslno ,X.DeptID,X.PrsLossPercent,X.ColId 
UNION ALL 
SELECT OrderMas.OrdID as GrpOrdID,   OrderMas.OrdId,''as Styleno, Mas_Commercial.Descr, PRo_BudCommercial.SlNo,  
 PRo_BudCommercial.Total AS Amount, 0 AS Expr1, 0 AS deptid,0 as PrsLossPercent,0 As ColId FROM  PRo_BudCommercial INNER JOIN  OrderMas ON  PRo_BudCommercial.OrdID = OrderMas.OrdId INNER JOIN  Mas_Commercial ON PRo_BudCommercial.ComID = Mas_Commercial.ID 
INNER JOIN  Vue_Rpt_OrdExcessQty ON OrderMas.OrdId = Vue_Rpt_OrdExcessQty.OrdID INNER JOIN Vue_Rpt_OrdQtywithSaleRate ON OrderMas.OrdId =  Vue_Rpt_OrdQtywithSaleRate.OrdID cross join  options    union all  /* For fabric Module  */SELECT  OrderMas.OrdID as
 GrpOrdID,   OrderMas.OrdId,''as Styleno, Mas_Commercial.Descr, PRo_BudCommercial.SlNo, CASE WHEN per >  0 THEN (Vue_Rpt_OrdExcessQty_Fabric.salesamt * crate) * per / 100 WHEN val > 0 THEN Vue_Rpt_OrdExcessQty_Fabric.qty * Val  ELSE Total END AS Amount, 0 AS Expr1, 0 AS deptid,0 as PrsLossPercent,0 As ColId FROM PRo_BudCommercial INNER JOIN  OrderMas ON  PRo_BudCommercial.OrdID = OrderMas.OrdId INNER JOIN  Mas_Commercial ON PRo_BudCommercial.ComID = Mas_Commercial.ID  INNER JOIN Vue_Rpt_OrdExcessQty_Fabric ON OrderMas.OrdId = Vue_Rpt_OrdExcessQty_Fabric.OrdID 