/**
 * /production/bundles — Bundle / Barcode Entry (SPEC-M5 §7-B-10, item
 * 'bundle-barcode', legacy FrmBundle_ProductionEntry / frmBarcodeReadingNew).
 * Bundle-NO-KEYED DS: ?bundle=CUT-0001/B1 (or a scanned barcode) resolves the
 * CutBundle server-side and PREFILLS the form (order/style/colour/size ride
 * the bundle; qty defaults to the bundle qty). The service re-resolves at
 * plan time — the prefill is UX only, the plan is the source of truth.
 * Views reuse /production/entry/[id].
 */
import { db } from '@/lib/db'
import { bundleBarcodeConfig, toScreenConfig } from '@/lib/erp/doc-configs'
import { DocScreen } from '@/components/archetypes/doc-screen'
import { DocBreadcrumb, RecentDocsTable } from '@/components/erp/recent-docs'

export const dynamic = 'force-dynamic'

export default async function BundleBarcodePage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | string[] | undefined>>
}) {
  const sp = await searchParams
  const bundleKey = typeof sp.bundle === 'string' ? sp.bundle.trim() : ''
  const order = typeof sp.order === 'string' ? sp.order : undefined

  // ?bundle= prefill — resolve the bundle (no OR barcode), seed the form.
  // CutBundle FKs are relation-less columns (PITFALLS #21) — resolve via lookups.
  let prefill: Record<string, string> | undefined
  if (bundleKey) {
    const bundle = await db.cutBundle.findFirst({
      where: { OR: [{ bundleNo: bundleKey }, { barcode: bundleKey }] },
    })
    if (bundle) {
      const cutOrder = bundle.cutOrderId
        ? await db.cutOrder.findUnique({ where: { id: bundle.cutOrderId } }).catch(() => null)
        : null
      const bundleOrder = cutOrder?.orderId
        ? await db.order.findUnique({ where: { id: cutOrder.orderId } }).catch(() => null)
        : null
      if (bundleOrder) {
        prefill = {
          bundleNo: bundle.bundleNo,
          qty: String(bundle.qty),
        }
      }
    }
  } else if (order) {
    prefill = {}
  }

  const recent = await db.productionEntry.findMany({
    where: { rework: false, bundleNo: { not: null } },
    orderBy: { prodDate: 'desc' },
    take: bundleBarcodeConfig.recentCount ?? 20,
    include: { order: true, department: true, operator: true },
  })
  const rows = recent.map((e) => ({
    id: e.id,
    cells: {
      orderNo: e.order?.orderNo ?? '—',
      bundleNo: e.bundleNo ?? '—',
      operatorName: e.operator?.name ?? '—',
      deptName: e.department?.name ?? e.department?.code ?? '—',
      prodDate: e.prodDate ? e.prodDate.toISOString().slice(0, 10) : '—',
      qty: (e.qty || 0).toLocaleString('en-IN'),
      amount: `₹${(e.amount || 0).toLocaleString('en-IN')}`,
    },
  }))
  return (
    <div className="space-y-5">
      <DocBreadcrumb href="/production" label="Production" title="Bundle / Barcode Entry" />
      <DocScreen
        config={toScreenConfig(bundleBarcodeConfig)}
        mode="new"
        viewRoutePattern="/production/entry/[id]"
        prefill={prefill}
      />
      <RecentDocsTable
        title="Recent bundle entries"
        columns={bundleBarcodeConfig.listColumns}
        rows={rows}
        hrefBase="/production/entry"
        empty="No bundle entries yet — scan the first bundle above (bundles are generated by cut orders)."
      />
    </div>
  )
}
