/*  
;=============================================  
; Author		   :  Global Software's  
; Create date	   :  10/04/2014  
; Create By		   :  Dharani A.
; Description	   :  Part Outstanding Ord wise Dept Arrival
; Change Person	   :  Dharani A.
; Last Change Date :  10/04/2014 3.30   
; =============================================  */
CREATE procedure Party_Outstanding_OrdwiseStk_Arrival(@Ordid int, @Party int, @Deptid int,@guid varchar(256))
as
Begin
insert into TempPartyBalAbs_all (guid,exportername,pname,Deptname,Ordid,Dckgs,DcMtr,deptid,pid) sELECT @guid, Mas_Exporter.ExporterName, Case when Trs_Del1.PartyUnit='P' then Mas_Party.Pname Else Unit.ExporterName End as Pname, Mas_Dept.Deptname, OrderMas.OrdId  ,SUM(Trs_Del2.Kg) AS Kg, SUM(Trs_Del2.mtr) AS mtr,Mas_Dept.DeptId,Trs_Del1.party  FROM Trs_Del1 INNER JOIN Trs_Del2 ON Trs_Del1.ID = Trs_Del2.ID INNER JOIN StockTable ON Trs_Del2.StockID = StockTable.StockID INNER JOIN Mas_Exporter ON Trs_Del1.Coycode = Mas_Exporter.ExpID INNER JOIN Mas_Dept ON Trs_Del1.Prs_Dept = Mas_Dept.DeptID INNER JOIN Mas_Party ON Trs_Del1.Party = Mas_Party.PID INNER JOIN OrderMas ON Trs_Del2.OrdID = OrderMas.OrdId  LEFT OUTER JOIN Mas_Exporter as Unit ON Trs_Del1.Party=Unit.ExpID  WHERE   trs_del2.ordid =@Ordid and trs_del1.prs_dept =@Deptid and trs_del1.party = @Party and Mas_dept.RecMethod='O'  and TrType=1 GROUP BY Mas_Exporter.ExporterName,Case when Trs_Del1.PartyUnit='P' then Mas_Party.Pname Else Unit.ExporterName End, OrderMas.OrdId,Mas_Dept.DeptId,Mas_Dept.Deptname,Trs_Del1.party 
             update  TempPartyBalAbs_all set TempPartyBalAbs_all.Reckgs = x.RecKgs from (SELECT Mas_Exporter.ExporterName, Mas_Dept.DeptId,Mas_Dept.Deptname,Mas_Party.Pname, OrderMas.OrdId, SUM(Trs_GRN2.RecKgs) AS RecKgs, SUM(Trs_GRN2.Recmtr) AS Recmtr,mas_party.Pid FROM Trs_Grn1 INNER JOIN Trs_GRN2 ON Trs_Grn1.ID = Trs_GRN2.ID  INNER JOIN StockTable ON Trs_GRN2.StockID = StockTable.StockID INNER JOIN Mas_Exporter ON Trs_Grn1.Coycode = Mas_Exporter.ExpID INNER JOIN Mas_Dept ON Trs_Grn1.Dept = Mas_Dept.DeptID INNER JOIN Mas_Party ON Trs_Grn1.SuppID = Mas_Party.PID INNER JOIN OrderMas ON StockTable.OrdID = OrderMas.OrdId  WHERE  (Trs_Grn1.GRNType in ('Process')) AND (Trs_Grn2.OrdID IN (SELECT DISTINCT Ordid FROM Trs_Del1 INNER JOIN Trs_Del2 ON Trs_Del1.ID=Trs_Del2.ID  WHERE ordid = Trs_grn2.ordid AND party = trs_grn1.suppid AND prs_dept = trs_grn1.dept  and  Mas_dept.RecMethod='O' and (ISNULL(Trs_DEl2.OrdwiseClose,'No')='No'))) and trs_grn2.ordid =@Ordid and trs_grn1.dept =@deptid and trs_grn1.suppid =@Party  GROUP BY Mas_Exporter.ExporterName, Mas_Party.Pname, OrderMas.OrdId,Mas_Dept.DeptId,Mas_Dept.Deptname,mas_party.Pid)x  inner join TempPartyBalAbs_all on TempPartyBalAbs_all.exportername=x.ExporterName and TempPartyBalAbs_all.deptid= x.deptid and TempPartyBalAbs_all.ordid= x.ordid  and TempPartyBalAbs_all.pid= x.pid and TempPartyBalAbs_all.guid=@guid
                update  TempPartyBalAbs_all set TempPartyBalAbs_all.Retkgs = x.RetKgs from (SELECT Mas_Exporter.ExporterName, Mas_Dept.DeptId,Mas_Dept.Deptname,Mas_Party.Pname, OrderMas.OrdId, SUM(Trs_GRN2.RecKgs) AS RetKgs, SUM(Trs_GRN2.Recmtr) AS Retmtr,mas_party.Pid FROM Trs_Grn1 INNER JOIN Trs_GRN2 ON Trs_Grn1.ID = Trs_GRN2.ID  INNER JOIN StockTable ON Trs_GRN2.StockID = StockTable.StockID INNER JOIN Mas_Exporter ON Trs_Grn1.Coycode = Mas_Exporter.ExpID INNER JOIN Mas_Dept ON Trs_Grn1.Dept = Mas_Dept.DeptID INNER JOIN Mas_Party ON Trs_Grn1.SuppID = Mas_Party.PID INNER JOIN OrderMas ON StockTable.OrdID = OrderMas.OrdId  WHERE  (Trs_Grn1.GRNType in ('Process Return')) AND  (Trs_Grn2.OrdID IN (SELECT DISTINCT Ordid FROM Trs_Del1 INNER JOIN Trs_Del2 ON Trs_Del1.ID=Trs_Del2.ID  WHERE ordid = Trs_grn2.ordid AND party = trs_grn1.suppid AND prs_dept = trs_grn1.dept  and  Mas_dept.RecMethod='O' and (ISNULL(Trs_DEl2.OrdwiseClose,'No')='No'))) and trs_grn2.ordid =@Ordid and trs_grn1.dept =@deptid and trs_grn1.suppid =@party GROUP BY Mas_Exporter.ExporterName, Mas_Party.Pname, OrderMas.OrdId,Mas_Dept.DeptId,Mas_Dept.Deptname,mas_party.Pid)x  inner join TempPartyBalAbs_all on TempPartyBalAbs_all.exportername=x.ExporterName and TempPartyBalAbs_all.deptid= x.deptid and TempPartyBalAbs_all.ordid= x.ordid  and TempPartyBalAbs_all.pid= x.pid and TempPartyBalAbs_all.guid=@guid
				-- ", ParamTbl) 'Trs_Grn1.Dept=4 and ordermas.buyerid in (8) and Ordermas.completed=0 and Ordermas.Ordertype='Order' and AND trs_grn1.coycode=1  

  --order by ordid 
  --select @tmpstr = @tmpstr + @Sqlstr exec sp_executesql @tmpstr,N'@Guid varchar(256)

End

