/*;=============================================   
; Author           :  Global Software's    
; Create date      :  18/05/2024    
; Create By        :  M.SUGANYA  
; Description      :  QUERY
; Change Person    :   M.SUGANYA  
; Last Change Date :  03/06/2024 10.30 AM 
; =============================================  */  

CREATE PROCEDURE SP_ConsQuery2_PcsGrn_1_Lot_OneSize_Ret (@Ordid int,@Styleno Varchar(30),@Coycode int,@StageID int, @DcId Int)
AS 

SELECT Prog_ClrComb.Yd, Prog_ClrComb.compID, Prog_ClrComb.ID, Prog_ClrComb.ClrCombID, Prog_ClrComb.FabClr, Prog_ClrComb.FabDesc, Prog_ClrComb.GreyGsm, Prog_ClrComb.FinalGsm, Prog_ClrComb.GG, Prog_ClrComb.LL, Prog_Cns.FABWIDTH AS FabWid, Prog_ClrComb.WtUom, Prog_ClrComb.LooseFab,  Prog_Cns.pcswgt, Prog_Cns.kdia, Prog_Cns.fdia, Prog_Cns.ldia, (Prodentry.ProdPcs) AS OrderQty, 0 AS Exs_Per, Prog_ClrComb.CompGrdSlno,  Prog_ClrComb.PExc, ISNULL(Prog_Cns.NoofPiece, 1) AS NoofPiece, CutPlanQty,0 as pcswt1, Prog_ClrComb.PartID FROM Prog_ClrComb INNER JOIN Prog_Cns ON Prog_ClrComb.ID = Prog_Cns.ID INNER JOIN  (select OrdID,StyleNo,SizeId,ColID,CmbClrID,PartId,  ISNULL(sum(OrderQtyDtl.CutPlanQty), 0) AS CutPlanQty from OrderQtyDtl where OrdID = @OrdId AND StyleNo = @StyleNo group by OrdID,StyleNo,SizeId,ColID,CmbClrID,PartId) OrderQtyDtl ON Prog_ClrComb.OrdID = OrderQtyDtl.OrdID AND Prog_ClrComb.StyleNo = OrderQtyDtl.StyleNo AND Prog_Cns.sizid = OrderQtyDtl.SizeId AND Prog_ClrComb.ClrCombID = OrderQtyDtl.ColID INNER JOIN 
(select Trs_PcsGrn1.id,Trs_PcsGrn1.OrdJob,Trs_PcsGrn2.StyleNo,ColID,LotNo,Trs_PcsGrn2.PARTID,TargetStageID,Coycode, FabDesc,(RecPcs) ProdPcs,SizId, Ourdcref from  Trs_PcsGrn1 inner  join Trs_PcsGrn2 on Trs_PcsGrn1.id=Trs_PcsGrn2.id inner join (select distinct PARTID,FabDesc,Ordid,StyleNo from Prog_ClrComb  WHERE Ordid = @Ordid and Styleno=@styleno )x on Trs_PcsGrn1.OrdJob=x.OrdID and  Trs_PcsGrn2.StyleNo=x.StyleNo and   Trs_PcsGrn2.PARTID=x.PartID  WHERE Trs_PcsGrn1.OrdJob = @Ordid and Trs_PcsGrn2.Styleno=@styleno and TargetStageID=-2 )
 Prodentry on Prodentry.OrdJob =OrderQtyDtl.OrdID  AND Prodentry.StyleNo = OrderQtyDtl.StyleNo and Prodentry.ColID = OrderQtyDtl.ColID   
   and   OrderQtyDtl.PartID  =Prodentry.PARTID  and  Prodentry.FabDesc = Prog_ClrComb.FabDesc   LEFT OUTER JOIN Prog_Component ON Prog_ClrComb.OrdID = Prog_Component.OrdID AND Prog_ClrComb.StyleNo = Prog_Component.StyleNo AND Prog_ClrComb.compID = Prog_Component.CompID AND Prog_ClrComb.ID = Prog_Component.sl INNER JOIN  (Select Distinct A.Ordid,A.Styleno,Stocktable.FabId,StockTable.Colid,StockTable.gsm,stocktable.fingsm,stocktable.gg,stocktable.ll, A.ID As Dcid From TRS_Del2 A  INNER JOIN Trs_Del1 B ON A.ID = B.ID  INNER JOIN StockTable ON Stocktable.Stockid = A.StockId Where TrType = 21 and Prs_Dept=11  and stocktable.YF='F' ) X ON X.FabID = Prog_ClrComb.FabDesc And X.colid = prog_clrcomb.fabclr And X.gsm = Prog_ClrComb.GreyGsm And X.FinGsm = Prog_ClrComb.FinalGsm and X.GG = Prog_ClrComb.GG  And X.LL = Prog_ClrComb.LL and X.ordid = OrderQtyDtl.Ordid and x.styleno = OrderQtyDtl.Styleno And x.Dcid = Prodentry.Ourdcref   WHERE     (Prog_ClrComb.OrdID = @OrdId) AND (Prog_ClrComb.StyleNo =  @StyleNo) and Prodentry.TargetStageID=1 and Prodentry.Coycode=@CoyCode and Prog_ClrComb.yd <> 1 And X.Dcid = @DcId group by Prog_ClrComb.Yd, Prog_ClrComb.compID, Prog_ClrComb.ID, Prog_ClrComb.ClrCombID, Prog_ClrComb.FabClr, Prog_ClrComb.FabDesc, Prog_ClrComb.GreyGsm, Prog_ClrComb.FinalGsm, Prog_ClrComb.GG, Prog_ClrComb.LL, Prog_Cns.FABWIDTH , Prog_ClrComb.WtUom, Prog_ClrComb.LooseFab,  Prog_Cns.pcswgt, Prog_Cns.kdia, Prog_Cns.fdia, Prog_Cns.ldia,  Prog_ClrComb.CompGrdSlno, Prog_ClrComb.PExc,OrderQtyDtl.CutPlanQty,Prog_Cns.NoofPiece  ,Prodentry.ProdPcs, Prog_ClrComb.PartID
   union all SELECT Prog_ClrComb.Yd, Prog_ClrComb.compID, Prog_ClrComb.ID, Prog_ClrComb.ClrCombID, Prog_ClrComb.Fincol, Prog_ClrComb.FabDesc, Prog_ClrComb.GreyGsm, Prog_ClrComb.FinalGsm, Prog_ClrComb.GG, Prog_ClrComb.LL, Prog_Cns.FABWIDTH AS FabWid, Prog_ClrComb.WtUom, Prog_ClrComb.LooseFab,  Prog_Cns.pcswgt, Prog_Cns.kdia, Prog_Cns.fdia, Prog_Cns.ldia, (Prodentry.ProdPcs) AS OrderQty, 0 AS Exs_Per, Prog_ClrComb.CompGrdSlno,  Prog_ClrComb.PExc, ISNULL(Prog_Cns.NoofPiece, 1) AS NoofPiece, ISNULL(OrderQtyDtl.CutPlanQty, 0)AS CutPlanQty, 0 As PcsWt1, Prog_ClrComb.PartID FROM Prog_ClrComb INNER JOIN Prog_Cns ON Prog_ClrComb.ID = Prog_Cns.ID INNER JOIN   (select OrdID,StyleNo,SizeId,ColID,CmbClrID,PartId,  ISNULL(sum(OrderQtyDtl.CutPlanQty), 0)AS CutPlanQty from OrderQtyDtl where OrdID = @OrdId AND StyleNo = @StyleNo group by OrdID,StyleNo,SizeId,ColID,CmbClrID,PartId)  OrderQtyDtl ON Prog_ClrComb.OrdID = OrderQtyDtl.OrdID AND Prog_ClrComb.StyleNo = OrderQtyDtl.StyleNo AND Prog_Cns.sizid = OrderQtyDtl.SizeId AND Prog_ClrComb.ClrCombID = OrderQtyDtl.ColID  INNER JOIN 
  (select Trs_PcsGrn1.id,Trs_PcsGrn1.OrdJob,Trs_PcsGrn2.StyleNo,ColID,LotNo,Trs_PcsGrn2.PARTID,TargetStageID,Coycode,FabDesc,(RecPcs) ProdPcs,SizId, Ourdcref from  Trs_PcsGrn1 inner  join Trs_PcsGrn2 on Trs_PcsGrn1.id=Trs_PcsGrn2.id inner join (select distinct PARTID,FabDesc,Ordid,StyleNo from Prog_ClrComb  WHERE Ordid = @Ordid and Styleno=@styleno )x on Trs_PcsGrn1.OrdJob=x.OrdID and  Trs_PcsGrn2.StyleNo=x.StyleNo and   Trs_PcsGrn2.PARTID=x.PartID  WHERE Trs_PcsGrn1.OrdJob = @Ordid and Trs_PcsGrn2.Styleno=@styleno and TargetStageID=-2 )
   Prodentry  on Prodentry .OrdJob =OrderQtyDtl.OrdID  AND Prodentry.StyleNo = OrderQtyDtl.StyleNo and Prodentry.ColID = OrderQtyDtl.ColID   and   OrderQtyDtl.PartID  =Prodentry.PARTID  and  Prodentry.FabDesc = Prog_ClrComb.FabDesc   LEFT OUTER JOIN Prog_Component ON Prog_ClrComb.OrdID = Prog_Component.OrdID AND Prog_ClrComb.StyleNo = Prog_Component.StyleNo AND Prog_ClrComb.compID = Prog_Component.CompID AND Prog_ClrComb.ID = Prog_Component.sl  INNER JOIN  (Select Distinct A.Ordid,A.Styleno,Stocktable.FabId,StockTable.Colid,StockTable.gsm,stocktable.fingsm,stocktable.gg,stocktable.ll, A.ID As Dcid From TRS_Del2 A  INNER JOIN Trs_Del1 B ON A.ID = B.ID  INNER JOIN StockTable ON Stocktable.Stockid = A.StockId Where TrType = 21 and Prs_Dept=11  and stocktable.YF='F' ) X ON X.FabID = Prog_ClrComb.FabDesc And X.colid = prog_clrcomb.fincol And X.gsm = Prog_ClrComb.GreyGsm And X.FinGsm = Prog_ClrComb.FinalGsm and X.GG = Prog_ClrComb.GG  And X.LL = Prog_ClrComb.LL and X.ordid = OrderQtyDtl.Ordid and x.styleno = OrderQtyDtl.Styleno And x.Dcid = Prodentry.Ourdcref    WHERE     (Prog_ClrComb.OrdID = @OrdId) AND (Prog_ClrComb.StyleNo =  @StyleNo) and Prodentry.TargetStageID=-2  and Prodentry.Coycode=@CoyCode and Prog_ClrComb.yd = 1 And X.Dcid = @DcId group by Prog_ClrComb.Yd, Prog_ClrComb.compID, Prog_ClrComb.ID, Prog_ClrComb.ClrCombID, Prog_ClrComb.Fincol, Prog_ClrComb.FabDesc, Prog_ClrComb.GreyGsm, Prog_ClrComb.FinalGsm, Prog_ClrComb.GG, Prog_ClrComb.LL, Prog_Cns.FABWIDTH , Prog_ClrComb.WtUom, Prog_ClrComb.LooseFab,  Prog_Cns.pcswgt, Prog_Cns.kdia, Prog_Cns.fdia, Prog_Cns.ldia,  Prog_ClrComb.CompGrdSlno, Prog_ClrComb.PExc,OrderQtyDtl.CutPlanQty,Prog_Cns.NoofPiece ,Prodentry.ProdPcs, Prog_ClrComb.PartID ORDER BY Prog_ClrComb.compID 