/*;=============================================   
; Author           :  Global Software's    
; Create date      :  10/04/2024    
; Create By        :  M.SUGANYA  
; Description      :  QUERY
; Change Person    :   M.SUGANYA  
; Last Change Date :  03/06/2024 09.30 AM 
; =============================================  */  


CREATE PROCEDURE SP_ConsQuery2_PcsGrnOneSize (@Ordid int,@Styleno Varchar(30),@Coycode int,@StageID int, @Id Int, @DcId Int)
AS 
SELECT Prog_ClrComb.Yd, Prog_ClrComb.compID, Prog_ClrComb.ID, Prog_ClrComb.ClrCombID, Prog_ClrComb.FabClr, Prog_ClrComb.FabDesc, Prog_ClrComb.GreyGsm, Prog_ClrComb.FinalGsm, Prog_ClrComb.GG, Prog_ClrComb.LL, Prog_Cns.FABWIDTH AS FabWid, Prog_ClrComb.WtUom, Prog_ClrComb.LooseFab, Prog_Cns.pcswgt, Prog_Cns.kdia, Prog_Cns.fdia, Prog_Cns.ldia, (Prodentry.ProdPcs) AS OrderQty, 0 AS Exs_Per, Prog_ClrComb.CompGrdSlno,  Prog_ClrComb.PExc, ISNULL(Prog_Cns.NoofPiece, 1) AS NoofPiece, ISNULL(OrderQtyDtl.CutPlanQty, 
0)AS CutPlanQty,PcsPerBit,PcsWt1,Prog_ClrComb.PartID  FROM Prog_ClrComb INNER JOIN Prog_Cns ON Prog_ClrComb.ID = Prog_Cns.ID INNER JOIN 
 (select OrdID,StyleNo,SizeId,ColID,CmbClrID,PartId,  ISNULL(sum(OrderQtyDtl.CutPlanQty), 0)AS CutPlanQty,Lotno from OrderQtyDtl where OrdID = @OrdId AND StyleNo = @StyleNo group by OrdID,StyleNo,SizeId,ColID,CmbClrID,PartId,Lotno) OrderQtyDtl ON Prog_ClrComb.OrdID = OrderQtyDtl.OrdID AND Prog_ClrComb.StyleNo = OrderQtyDtl.StyleNo AND Prog_Cns.sizid = OrderQtyDtl.SizeId AND Prog_ClrComb.ClrCombID = OrderQtyDtl.ColID 
  INNER JOIN  (Select Distinct ORdid,Styleno,bitsizeID,Wrk_ID,Partid,DesignDescription,IsNull(pcswt,0) as PcsWt1,NoofPcsPer_Bit As PcsPerBit FROM Pro_Prod_BitCutRate inner join Mas_Size on Pro_Prod_BitCutRate.BitSizeID = Mas_Size.SizeID ) BB   on BB.Ordid = OrderQtyDtl.OrdID AND BB.Styleno = OrderQtyDtl.StyleNo AND BB.Partid = OrderQtyDtl.PartID  INNER JOIN  (select Trs_PcsGrn1.id,Trs_PcsGrn1.OrdJob,Trs_PcsGrn2.StyleNo,ColID,LotNo,Trs_PcsGrn2.PARTID,TargetStageID,Coycode,FabDesc,(RecPcs) ProdPcs,SizId,BitFormDesignDesc from  Trs_PcsGrn1 inner  join Trs_PcsGrn2 on Trs_PcsGrn1.id=Trs_PcsGrn2.id inner join (select distinct PARTID,FabDesc,Ordid,StyleNo from Prog_ClrComb  WHERE Ordid = @Ordid and Styleno=@styleno )x on Trs_PcsGrn1.OrdJob=x.OrdID and  Trs_PcsGrn2.StyleNo=x.StyleNo and   Trs_PcsGrn2.PARTID=x.PartID 
     WHERE Trs_PcsGrn1.OrdJob = @Ordid and Trs_PcsGrn2.Styleno=@styleno and TargetStageID=@StageID And Trs_PcsGrn1.ID = @Id ) Prodentry   
     on Prodentry .OrdJob =OrderQtyDtl.OrdID  AND Prodentry.StyleNo = OrderQtyDtl.StyleNo and Prodentry.ColID = OrderQtyDtl.ColID    and Prodentry.PARTID = OrderQtyDtl.PartID   and  Prodentry.FabDesc = Prog_ClrComb.FabDesc   AND  Prodentry.BitFormDesignDesc = BB.DesignDescription       AND BB.DesignDescription = Prodentry.BitFormDesignDesc   And BB.Wrk_ID = Prodentry.TargetStageID  	 	   LEFT OUTER JOIN Prog_Component ON Prog_ClrComb.OrdID = Prog_Component.OrdID AND Prog_ClrComb.StyleNo = Prog_Component.StyleNo AND Prog_ClrComb.compID = Prog_Component.CompID AND Prog_ClrComb.ID = Prog_Component.sl INNER JOIN  (
	 	 Select Distinct A.Ordid,A.Styleno,Stocktable.FabId,StockTable.Colid,StockTable.gsm,stocktable.fingsm,stocktable.gg,stocktable.ll, A.id As DcId From TRS_Del2 A  INNER JOIN Trs_Del1 B ON A.ID = B.ID  INNER JOIN StockTable ON Stocktable.Stockid = A.StockId Where TrType = 21 and Prs_Dept=11  and stocktable.YF='F'
	 	 	  ) X ON X.FabID = Prog_ClrComb.FabDesc And X.colid = prog_clrcomb.fabclr And X.gsm = Prog_ClrComb.GreyGsm And X.FinGsm = Prog_ClrComb.FinalGsm and X.GG = Prog_ClrComb.GG  And X.LL = Prog_ClrComb.LL and X.ordid = OrderQtyDtl.Ordid and x.styleno = OrderQtyDtl.Styleno And Prodentry.Lotno=OrderQtyDtl.Lotno  WHERE     (Prog_ClrComb.OrdID = @OrdId) AND (Prog_ClrComb.StyleNo =  @StyleNo) and Prodentry.TargetStageID=@StageId and Prodentry.Coycode=@Coycode and Prog_ClrComb.yd <> 1  And Prodentry.ID = @Id And X.DcId = @DcId
	 	  group by Prog_ClrComb.Yd,  Prog_ClrComb.compID, Prog_ClrComb.ID, Prog_ClrComb.ClrCombID, Prog_ClrComb.FabClr, Prog_ClrComb.FabDesc, Prog_ClrComb.GreyGsm, Prog_ClrComb.FinalGsm, Prog_ClrComb.GG, Prog_ClrComb.LL, Prog_Cns.FABWIDTH , Prog_ClrComb.WtUom, Prog_ClrComb.LooseFab,  Prog_Cns.pcswgt, Prog_Cns.kdia, Prog_Cns.fdia, Prog_Cns.ldia,  Prog_ClrComb.CompGrdSlno, Prog_ClrComb.PExc,OrderQtyDtl.CutPlanQty,Prog_Cns.NoofPiece,PcsPerBit ,PcsWt1,Prodentry.ProdPcs,Prog_ClrComb.PartID	  		   
		  	    UNION ALL SELECT Prog_ClrComb.Yd, Prog_ClrComb.compID, Prog_ClrComb.ID, Prog_ClrComb.ClrCombID, Prog_ClrComb.Fincol, Prog_ClrComb.FabDesc, Prog_ClrComb.GreyGsm, Prog_ClrComb.FinalGsm, Prog_ClrComb.GG, Prog_ClrComb.LL, Prog_Cns.FABWIDTH AS FabWid, Prog_ClrComb.WtUom, Prog_ClrComb.LooseFab,  Prog_Cns.pcswgt, Prog_Cns.kdia, Prog_Cns.fdia, Prog_Cns.ldia, (Trs_PcsGrn2.RecPcs) AS OrderQty, 0 AS Exs_Per, Prog_ClrComb.CompGrdSlno,  Prog_ClrComb.PExc, ISNULL(Prog_Cns.NoofPiece, 1) AS NoofPiece, ISNULL(OrderQtyDtl.CutPlanQty, 0)AS CutPlanQty,PcsPerBit,PcsWt1,Prog_ClrComb.PartID FROM Prog_ClrComb INNER JOIN Prog_Cns ON Prog_ClrComb.ID = Prog_Cns.ID INNER JOIN  (select OrdID,StyleNo,SizeId,ColID,CmbClrID,PartId, Lotno, ISNULL(sum(OrderQtyDtl.CutPlanQty), 0)AS CutPlanQty from OrderQtyDtl where OrdID = @OrdId AND StyleNo = @StyleNo group by OrdID,StyleNo,SizeId,ColID,CmbClrID,PartId,Lotno)  OrderQtyDtl ON Prog_ClrComb.OrdID = OrderQtyDtl.OrdID AND Prog_ClrComb.StyleNo = OrderQtyDtl.StyleNo AND Prog_Cns.sizid = OrderQtyDtl.SizeId AND Prog_ClrComb.ClrCombID = OrderQtyDtl.ColID  
INNER JOIN (Select Distinct ORdid,Styleno,bitsizeID,Wrk_ID,Partid,DesignDescription,IsNull(pcswt,0) as PcsWt1, NoofPcsPer_Bit As PcsPerBit FROM Pro_Prod_BitCutRate inner join Mas_Size on Pro_Prod_BitCutRate.BitSizeID = Mas_Size.SizeID ) BB on BB.Ordid = OrderQtyDtl.OrdID AND BB.Styleno = OrderQtyDtl.StyleNo AND BB.Partid = OrderQtyDtl.PartID    INNER JOIN      (select Trs_PcsGrn1.id,Trs_PcsGrn1.OrdJob,Trs_PcsGrn2.StyleNo,ColID,LotNo,Trs_PcsGrn2.PARTID,TargetStageID,Coycode,FabDesc,(RecPcs) ProdPcs,SizId,BitFormDesignDesc from  Trs_PcsGrn1 inner  join Trs_PcsGrn2 on Trs_PcsGrn1.id=Trs_PcsGrn2.id inner join (select distinct PARTID,FabDesc,Ordid,StyleNo from Prog_ClrComb  WHERE Ordid = @Ordid and Styleno=@styleno )x       on Trs_PcsGrn1.OrdJob=x.OrdID and  Trs_PcsGrn2.StyleNo=x.StyleNo and   Trs_PcsGrn2.PARTID=x.PartID  WHERE Trs_PcsGrn1.OrdJob = @Ordid and Trs_PcsGrn2.Styleno=@styleno and TargetStageID=@StageID And Trs_PcsGrn1.ID = @Id) Prodentry on Prodentry.OrdJob =OrderQtyDtl.OrdID  AND Prodentry.StyleNo = OrderQtyDtl.StyleNo and Prodentry.ColID = OrderQtyDtl.ColID     AND Prodentry.BitFormDesignDesc = BB.DesignDescription AND BB.DesignDescription = Prodentry.BitFormDesignDesc    And BB.Wrk_ID = Prodentry.TargetStageID    inner join Trs_PcsGrn2 on Prodentry.id=Trs_PcsGrn2.id  and   OrderQtyDtl.PartID  =Prodentry.PARTID   and Prodentry.LotNo = OrderQtyDtl.LotNo and  Prodentry.FabDesc = Prog_ClrComb.FabDesc LEFT OUTER JOIN Prog_Component ON Prog_ClrComb.OrdID = Prog_Component.OrdID AND Prog_ClrComb.StyleNo = Prog_Component.StyleNo AND Prog_ClrComb.compID = Prog_Component.CompID AND Prog_ClrComb.ID = Prog_Component.sl INNER JOIN  (Select Distinct A.Ordid,A.Styleno,Stocktable.FabId,StockTable.Colid,StockTable.gsm,stocktable.fingsm,stocktable.gg,stocktable.ll, A.ID As DcId From TRS_Del2 A  INNER JOIN Trs_Del1 B ON A.ID = B.ID  INNER JOIN StockTable ON Stocktable.Stockid = A.StockId Where TrType = 21 and Prs_Dept=11  and stocktable.YF='F' ) X ON X.FabID = Prog_ClrComb.FabDesc And X.colid = prog_clrcomb.fincol And X.gsm = Prog_ClrComb.GreyGsm And X.FinGsm = Prog_ClrComb.FinalGsm and X.GG = Prog_ClrComb.GG  And X.LL = Prog_ClrComb.LL and X.ordid = OrderQtyDtl.Ordid and x.styleno = OrderQtyDtl.Styleno And Prodentry.Lotno=OrderQtyDtl.Lotno  WHERE     (Prog_ClrComb.OrdID = @OrdId) AND (Prog_ClrComb.StyleNo =  @StyleNo) and Prodentry.TargetStageID=@StageID and Prodentry.Coycode=@Coycode and Prog_ClrComb.yd = 1 And Prodentry.ID = @Id And X.DcId = @DcId group by Prog_ClrComb.Yd, Prog_ClrComb.compID, Prog_ClrComb.ID, Prog_ClrComb.ClrCombID, Prog_ClrComb.Fincol, Prog_ClrComb.FabDesc, Prog_ClrComb.GreyGsm, Prog_ClrComb.FinalGsm, Prog_ClrComb.GG, Prog_ClrComb.LL, Prog_Cns.FABWIDTH , Prog_ClrComb.WtUom, Prog_ClrComb.LooseFab,  Prog_Cns.pcswgt, Prog_Cns.kdia, Prog_Cns.fdia, Prog_Cns.ldia,  Prog_ClrComb.CompGrdSlno, Prog_ClrComb.PExc,OrderQtyDtl.CutPlanQty,Prog_Cns.NoofPiece,PcsPerBit,PcsWt1,Trs_PcsGrn2.RecPcs,Prog_ClrComb.PartID ORDER BY Prog_ClrComb.compID