/*;=============================================   
; Author           :  Global Software's    
; Create date      :  20/08/2015    
; Create By        :  POOMANI  
; Description      :  Accessories_Stock  
; Change Person    :  ASLAM
; Last Change Date :  02/07/2021 10.30 AM 
; =============================================  */  
CREATE  PROCEDURE SP_Rpt_AccToDoIssProdUnit (@Coycode as int,@BuyerID as NVarchar(4000),@Styleno as NVarchar(4000), @OrdId as Nvarchar(4000),@AccTypeId as Nvarchar(4000),@OrderType as char(6),@ordstatus as int) AS BEGIN DECLARE @SQLSTR AS NVARCHAR(max) SET 
@SQLSTR=N'SELECT X.ordJobNo,X.OrdFinyear,X.BuyOrdNo,X.CutOrdJobNo,X.CutJobfinyear,X.AccTypeId ,X.Acc_Descr, X.AccDescId,X.AccDescription,ISNULL( X.ColorDesc,'''') ColorDesc,ISNULL(X.ColID,0) ColID, ISNULL(X.SizeDesc,'''') SizeDesc,ISNULL(X.SizeID,0) SizeID, X.Uom, X.Id, X.OrdID, X.StyleNo,ISNULL( X.SNo,0)SNo,0 as Req, 0 as Pcs, X.OrdQty, X.Multiple_Factor, X.Divide_Factor, X.ReqdQty, X.Sewflg,X.PartID,X.PartName,Sum(X.Stock) as Stock,Sum(ISNULL(X.JobIssQty,0)) as JobIssQty,X.JobOrdDate,X.Expid,X.Completed,X.OrderType,X.BuyerID,X.Acc_Type  FROM (SELECT DISTINCT ordermas.Jobno ordJobNo,OrderMas.Finyear OrdFinyear,OrderMas.BuyOrdNo,Cutting_Job.JobNo CutOrdJobNo,Cutting_Job.Finyear as CutJobfinyear,Mas_Acc.ID AS AccTypeId ,Mas_Acc.Acc_Descr,  Mas_AccDes.ID AccDescId,Mas_AccDes.AccDescription,ISNULL( Mas_Color.ColorDesc,'''') ColorDesc,ISNULL(Mas_Color.ColID,0) ColID, ISNULL(Mas_Size.SizeDesc,'''') SizeDesc,ISNULL(Mas_Size.SizeID,0) SizeID, Mas_Uom.Uom, Cutting_Job.Id, Cutting_Job.OrdID, Cutting_Job.StyleNo,ISNULL(
 OrdSizeMas.SNo,0)SNo, 0 as Req, 0 as Pcs, Vue_Pro_AccJobReq.OrdQty, Mas_Acc.Multiple_Factor, Mas_Acc.Divide_Factor, Vue_Pro_AccJobReq.oRDQTY ReqdQty, Vue_Pro_AccJobReq.Sewflg,Mas_Part.PartID,Mas_Part.PartName,Currentstock.Kg as 
Stock,ISNULL(y.Kg,0) as JobIssQty,Cutting_Job.JobOrdDate,Ordermas.Expid,Ordermas.Completed, OrderMas.OrderType,OrderMas.BuyerID,Vue_Pro_AccJobReq.Acc_Type  FROM   Cutting_Job Cutting_Job INNER JOIN Vue_Pro_AccJobReq Vue_Pro_AccJobReq 
ON Cutting_Job.OrdID=Vue_Pro_AccJobReq.OrdID AND Cutting_Job.StyleNo=Vue_Pro_AccJobReq.StyleNo AND Cutting_Job.Id=Vue_Pro_AccJobReq.JobOrdID LEFT OUTER JOIN OrdSizeMas OrdSizeMas ON Vue_Pro_AccJobReq.OrdID=OrdSizeMas.OrdID AND Vue_Pro_AccJobReq.Siz=OrdSizeMas.SizeID AND Vue_Pro_AccJobReq.StyleNo=OrdSizeMas.StyleNo INNER JOIN Mas_Acc Mas_Acc ON Vue_Pro_AccJobReq.Acc_Type=Mas_Acc.ID INNER JOIN Mas_AccDes Mas_AccDes ON Vue_Pro_AccJobReq.Acc_Desc=Mas_AccDes.ID LEFT OUTER JOIN Mas_Color Mas_Color ON Vue_Pro_AccJobReq.Clr=Mas_Color.ColID LEFT OUTER JOIN Mas_Size Mas_Size ON Vue_Pro_AccJobReq.Siz=Mas_Size.SizeID INNER JOIN Mas_Uom Mas_Uom ON Mas_Acc.UomId=Mas_Uom.UomID INNER JOIN OrderMas ON OrderMas.OrdId=Vue_Pro_AccJobReq.OrdID INNER JOIN Cutting_Job_Dtl ON Cutting_Job_Dtl.ID=Cutting_Job.ID INNER JOIN Mas_Part ON Mas_Part.PartID=Cutting_Job_Dtl.PartId inner join Mas_Buyer on OrderMas.BuyerID=Mas_Buyer.BuyerID left join StockTable on StockTable.OrdID=Vue_Pro_AccJobReq.OrdId and  StockTable.Ades=Vue_Pro_AccJobReq.Acc_Desc and  StockTable.Atype=Vue_Pro_AccJobReq.Acc_Type and StockTable.Siz=Vue_Pro_AccJobReq.Siz  and StockTable.OrdID=Cutting_Job.OrdId left join Currentstock on Currentstock.Ordid=OrderMas.OrdId and Currentstock.styleno=Vue_Pro_AccJobReq.StyleNo  and Cutting_Job.OrdID= Currentstock.ordid and Currentstock.ordid=Vue_Pro_AccJobReq.OrdID and StockTable.StockID=Currentstock.StockID and  StockTable.OrdID=Currentstock.OrdId  and Currentstock.styleno=Vue_Pro_AccJobReq.StyleNo  and Currentstock.styleno=Cutting_Job.StyleNo left join (select a.id,OrdId,b.StyleNo,b.StockID,sum(Kg) Kg from trs_del1 a inner join trs_del2 b on a.id=b.id where TrType=7 and Prs_Dept=16 and JobOrdID<>0 group by a.id,OrdId,b.StyleNo,b.StockID)y on y.OrdId=OrderMas.OrdId and y.OrdId=Vue_Pro_AccJobReq.OrdId and y.OrdId=Cutting_Job.OrdId and  y.OrdId=StockTable.OrdId and y.OrdId=Currentstock.OrdId  and y.StyleNo=Vue_Pro_AccJobReq.StyleNo and y.StyleNo=Cutting_Job.StyleNo and  y.StyleNo=Currentstock.styleno  and y.StockID=Currentstock.Stockid and y.StockID=StockTable.StockID)X WHERE X.OrdQty>0 and   X.Expid=@Coycode ' if len(rtrim(@BuyerID))>0  BEGIN SET @SQLSTR=@SQLSTR+N' AND X.BuyerId in (Select ID From fnSplitter(@BuyerId))' End if len(rtrim(@Styleno))>0  BEGIN SET @SQLSTR=@SQLSTR+N' AND X.Styleno in (Select IDstr From fnSplitter_str(@Styleno))' End if len(rtrim(@OrdID))>0  BEGIN SET @SQLSTR=@SQLSTR+N' AND X.OrdId in (Select ID From fnSplitter(@OrdId))' End if len(rtrim(@AccTypeId))>0 BEGIN SET @SQLSTR=@SQLSTR+N' AND X.Acc_Type in (Select ID From fnSplitter(@AccTypeId)) ' End if len(rtrim(@OrderType))>0 BEGIN SET @SQLSTR=@SQLSTR+N' AND X.OrderType=@OrderType' End  if @ordstatus <> 2 BEGIN SET @SQLSTR=@SQLSTR+N' AND X.Completed=@ordstatus ' End 
 BEGIN SET @SQLSTR=@SQLSTR+N'
group by X.ordJobNo,X.OrdFinyear,X.BuyOrdNo,X.CutOrdJobNo,X.CutJobfinyear,X.AccTypeId ,X.Acc_Descr, X.AccDescId,X.AccDescription,ISNULL( X.ColorDesc,'''') ,ISNULL(X.ColID,0) , ISNULL(X.SizeDesc,'''') ,ISNULL(X.SizeID,0) , X.Uom, X.Id, X.OrdID, X.StyleNo,ISNULL( X.SNo,0), X.OrdQty, X.Multiple_Factor, X.Divide_Factor, X.ReqdQty, X.Sewflg,X.PartID,X.PartName,X.JobOrdDate,X.Expid,X.Completed,X.OrderType,X.BuyerID,X.Acc_Type' end  
EXEC SP_EXECUTESQL @SQLSTR,N'@Coycode int,@BuyerID as NVarchar(4000),@Styleno as NVarchar(4000),@OrdId Nvarchar(4000),@AccTypeId Nvarchar(4000),@OrderType as char(6),@ordstatus as int',@Coycode=@Coycode,@BuyerID=@BuyerID,@Styleno=@Styleno,@OrdId=@OrdId,@AccTypeId=@AccTypeId,@OrderType=@OrderType,@ordstatus=@ordstatus End