/*;=============================================   
; Author           :  Global Software's    
; Create date      :  17/08/2022    
; Create By        :  ASLAM  
; Description      :  QUERY
; Change Person    :  ASLAM
; Last Change Date :  05/06/2025 10.00 AM 
; =============================================  */  
CREATE PROCEDURE SP_Rpt_AccStockItemLedger (@Coycode as int,@BuyerID as NVarchar(4000),@MerchId as NVarchar(4000), @OrdId as Nvarchar(4000),@AccTypeId as Nvarchar(4000),@StyleNo as Nvarchar(4000),@OrderType as char(6),@ordstatus as int) AS BEGIN DECLARE @SQLSTR AS NVARCHAR(4000) SET @SQLSTR=N' SELECT Distinct    OrderMas.Jobno, OrderMas.BuyerId,OrderMas.MerchId, Mas_Exporter.ExporterName, OrderMas.Finyear, OrderMas.BuyOrdNo,Vue_Rpt_AccStockItemLedgerAbs.StyleNo, Mas_Acc.Acc_Descr, Mas_Uom.Uom, Mas_AccDes.
AccDescription,Mas_Color.ColorDesc, Mas_Size.SizeDesc, dbo.FN_Add_BoostupPer(SUM(Vue_Rpt_AccStockItemLedgerAbs.ReqQty+Vue_Rpt_AccStockItemLedgerAbs.ShortageKgs)) AS ReqQty,dbo.FN_Add_BoostupPer(SUM(Vue_Rpt_AccStockItemLedgerAbs.POQty - Vue_Rpt_AccStockItemLedgerAbs.PoCanQty)) AS POQty, dbo.FN_Add_BoostupPer(SUM(Vue_Rpt_AccStockItemLedgerAbs.RecQty)) AS RecQty,dbo.FN_Add_BoostupPer(SUM(Vue_Rpt_AccStockItemLedgerAbs.DelQty)) AS DelQty, dbo.FN_Add_BoostupPer(SUM(Vue_Rpt_AccStockItemLedgerAbs.RetQty)) AS RetQty, dbo.FN_Add_BoostupPer(SUM(Vue_Rpt_AccStockItemLedgerAbs.StockQty)) AS StockQty, dbo.FN_Add_BoostupPer(SUM(Vue_Rpt_AccStockItemLedgerAbs.TranOutQty)) AS TranOutQty, dbo.FN_Add_BoostupPer(SUM(Vue_Rpt_AccStockItemLedgerAbs.TranInQty)) AS TranInQty, Vue_Rpt_AccStockItemLedgerAbs.Coycode, Vue_Rpt_AccStockItemLedgerAbs.OrdID, Mas_Acc.NoDec, OrderStyleDtl.SlNo AS StyleSlno, PRO_AccReq.SlNo AS AccSlno, OrdSizeMas.SNo AS SizeSlno, dbo.FN_Add_BoostupPer(SUM(Vue_Rpt_AccStockItemLedgerAbs.ProRetQty)) AS ProRetQty,dbo.FN_Add_BoostupPer(SUM(Vue_Rpt_AccStockItemLedgerAbs.ProRecQty)) AS ProRecQty, dbo.FN_Add_BoostupPer(SUM(Vue_Rpt_AccStockItemLedgerAbs.shortagekgs)) as shortqty  FROM  Vue_Rpt_AccStockItemLedgerAbs INNER JOIN OrderMas ON Vue_Rpt_AccStockItemLedgerAbs.OrdID = OrderMas.OrdId INNER JOIN Mas_Exporter ON Vue_Rpt_AccStockItemLedgerAbs.Coycode = Mas_Exporter.ExpID INNER JOIN Mas_Acc ON Vue_Rpt_AccStockItemLedgerAbs.AType = Mas_Acc.ID INNER JOIN Mas_AccDes ON Vue_Rpt_AccStockItemLedgerAbs.ADes = Mas_AccDes.ID INNER JOIN   (Select Ordid, Acc_Type, Acc_Desc, Clr, Siz, StyleNo, Min(Slno) Slno 

From Pro_accreq Group by  Ordid, Acc_Type, Acc_Desc, Clr, Siz, StyleNo)   PRO_AccReq  ON Vue_Rpt_AccStockItemLedgerAbs.OrdID = PRO_AccReq.OrdID AND Vue_Rpt_AccStockItemLedgerAbs.AType = PRO_AccReq.Acc_Type AND Vue_Rpt_AccStockItemLedgerAbs.ADes = PRO_AccReq.Acc_Desc AND Vue_Rpt_AccStockItemLedgerAbs.ACol = PRO_AccReq.Clr AND  Vue_Rpt_AccStockItemLedgerAbs.ASize = PRO_AccReq.Siz AND Vue_Rpt_AccStockItemLedgerAbs.StyleNo = PRO_AccReq.StyleNo LEFT OUTER JOIN (Select ordid,styleno,colid,SizeId  from OrderQtyDtl   group by ordid,styleno,colid,SizeId) as OrderQtyDtl ON Vue_Rpt_AccStockItemLedgerAbs.OrdID
 = OrderQtyDtl.OrdID AND  Vue_Rpt_AccStockItemLedgerAbs.StyleNo = OrderQtyDtl.StyleNo AND Vue_Rpt_AccStockItemLedgerAbs.ACol = OrderQtyDtl.ColID AND Vue_Rpt_AccStockItemLedgerAbs.ASize = OrderQtyDtl.SizeId LEFT OUTER JOIN OrdSizeMas ON OrderMas.OrdId = OrdSizeMas.OrdID AND Vue_Rpt_AccStockItemLedgerAbs.ASize = OrdSizeMas.SizeID And Vue_Rpt_AccStockItemLedgerAbs.StyleNo = OrdSizeMas.StyleNo 
  left outer join OrderStyleDtl on ordermas.ordid = OrderStyleDtl.OrdID and OrderQtyDtl.StyleNo = OrderStyleDtl.StyleNo 
 LEFT OUTER JOIN Mas_Size ON Vue_Rpt_AccStockItemLedgerAbs.ASize = Mas_Size.SizeID LEFT OUTER JOIN  Mas_Color ON Vue_Rpt_AccStockItemLedgerAbs.ACol = Mas_Color.ColID LEFT OUTER JOIN Mas_Uom ON Mas_Acc.UomId = Mas_Uom.UomID   WHERE Vue_Rpt_AccStockItemLedgerAbs.cOYCODE=@Coycode ' if len(rtrim(@BuyerID))>0  BEGIN SET @SQLSTR=@SQLSTR+N' AND OrderMas.BuyerId in (Select ID From fnSplitter(@BuyerId))' End if len(rtrim(@MerchId))>0  BEGIN SET @SQLSTR=@SQLSTR+N' AND OrderMas.MerchId in (Select ID From fnSplitter(@MerchId))' End if len(rtrim(@OrdID))>0  BEGIN SET @SQLSTR=@SQLSTR+N' AND Vue_Rpt_AccStockItemLedgerAbs.OrdId in (Select ID From fnSplitter(@OrdId))' End if len(rtrim(@AccTypeId))>0 BEGIN SET @SQLSTR=@SQLSTR+N' AND Vue_Rpt_AccStockItemLedgerAbs.AType in (Select ID From fnSplitter(@AccTypeId)) ' End  If Len(Rtrim(@StyleNo))>0 Begin Set @SQLSTR=@SQLSTR+N' AND Vue_Rpt_AccStockItemLedgerAbs.StyleNo in (Select IDStr From fnSplitter_Str(@StyleNO))' End if len(rtrim(@OrderType))>0 BEGIN SET @SQLSTR=@SQLSTR+N' AND OrderMas.OrderType=@OrderType' End if @ordstatus <> 2 BEGIN SET @SQLSTR=@SQLSTR+N' AND OrderMas.Completed=@ordstatus ' End BEGIN SET @SQLSTR=@SQLSTR+N' GROUP BY OrderMas.Jobno, orderMas.BuyerId,OrderMas.MerchId,Mas_Exporter.ExporterName, OrderMas.Finyear, OrderMas.BuyOrdNo, Vue_Rpt_AccStockItemLedgerAbs.StyleNo, Mas_Acc.Acc_Descr, Mas_Uom.Uom, Mas_AccDes.AccDescription,OrderStyleDtl.slno
, Mas_Color.ColorDesc, Mas_Size.SizeDesc, Vue_Rpt_AccStockItemLedgerAbs.Coycode, Vue_Rpt_AccStockItemLedgerAbs.OrdID, Mas_Acc.NoDec,  OrdSizeMas.SNo, PRO_AccReq.SlNo ' End EXEC SP_EXECUTESQL @SQLSTR,N'@Coycode int,@BuyerID as NVarchar(4000),@MerchId as NVarchar(4000),@OrdId Nvarchar(4000),@AccTypeId Nvarchar(4000),@StyleNo as Nvarchar(4000),@OrderType as char(6),@ordstatus as int',@Coycode=@Coycode,@BuyerID=@BuyerID,@MerchId=@MerchId,@OrdId=@OrdId,@AccTypeId=@AccTypeId,@Styleno=@Styleno,@OrderType=@OrderType,@ordstatus=@ordstatus End
