/*;=============================================   
; Author           :  Global Software's    
; Create date      :  20/09/2024    
; Create By        :  M.SUGANYA  
; Description      :  QUERY
; Change Person    :  M.SUGANYA
; Last Change Date :  09/10/2024 10.00 AM 

; =============================================  */  

CREATE PROCEDURE Spl_Bills_InvPcs_Supplier (@ordid as nvarchar(200)) AS BEGIN DECLARE @SQLSTR as nvarchar(4000) SET @SQLSTR=N'SELECT Trs_Bills.BillType, Trs_Bills.ID, Trs_Bills.brno, Trs_Bills.billamt, Trs_Bills.brdt, Mas_JobWrkComp.WorkComplDet As Deptname, Mas_Acc.Acc_Descr, Mas_StyleDesc.StyleDesc, Mas_Mill.Mill, Mas_Fabric.Fabdesc, Mas_AccDes.AccDescription, Mas_Dia.Dia, Trs_Bills.billno, Trs_Bills.billdt, Mas_Color.ColorDesc, Trs_Bills.coycode, Mas_Exporter.ExporterName,  Case when mas_dept.Proddept =''Y'' then ISNULL(Mas_Size1.SizeDesc,'''') Else Mas_Size.SizeDesc End As SizeDesc, Mas_Count.CountName, Trs_BillRate.Ades, Mas_Party.Pname, Trs_BillRate.Amount, Trs_BillRate.Rate, IsNull(Trs_BillDeb2.Rate,0) As DebitRate,IsNull(Trs_BillDeb2.Amount,0) As DebitAmount,IsNull(Trs_BillDeb2.Reason,'''') As DebitReason, IsNull(Trs_BillDeb1.DNo,0) As DebitNo, IsNull(Trs_BillDeb1.FinYear,'''') As DebitFinYear, Trs_BillRate.Mtr, Trs_BillRate.Kgs, Trs_BillRate.Rls, Mas_Dept.RateMethod,case when isnull(trs_billrate.Compid,0) =0 then Mas_Part.partname else MaS_part.PartName  end  as PanelName,Mas_Component.CompDescr as Comppanel  , Trs_Bills.finyear, Trs_Bills.remarks, ISNULL(OrderMas.Finyear, OrderMas_1.Finyear) AS OrdFinyear, ISNULL(OrderMas.Jobno, OrderMas_1.Jobno) AS OrdJobNo, ISNULL(OrderMas.BuyOrdNo, OrderMas_1.BuyOrdNo) AS BuyOrdNo, isnull(Vue_BillGrn.OrdID,orderMas.Ordid) as OrdId , Case when mas_dept.Proddept =''Y'' then ''Pcs'' else ''Mtrs'' End as Label,IsNull(Trs_BillRate.TaxPer,0) as TaxPer,IsNull(Trs_BillRate.TaxAmt,0) as TaxAmt, 0 as SampleKgs,0 as SampleAmt ,isNull(Dis_Percent,0) as Dis_Percent , isNull(DisAmt,0) as DisAmt , isNull(Amount1,0) as TaxableAmt ,Trs_BillRate.Styleno,Mas_User.Username FROM Mas_Size RIGHT OUTER JOIN Trs_Bills INNER JOIN Trs_BillRate ON Trs_Bills.ID = Trs_BillRate.ID LEFT OUTER JOIN Vue_BillGrn ON Trs_Bills.ID = Vue_BillGrn.ID
 AND Trs_BillRate.OrdID = Vue_BillGrn.OrdID Left Outer Join Trs_BillDeb1 On Trs_Bills.Id=Trs_BillDeb1.Brnid Left Outer Join Trs_BillDeb2 On Trs_BillDeb1.Id=Trs_BillDeb2.Id And Trs_BillRate.PoId=Trs_BillDeb2.PoId LEFT OUTER JOIN OrderMas ON Trs_BillRate.OrdID = OrderMas.OrdId LEFT OUTER JOIN Mas_Acc ON Trs_BillRate.Atype = Mas_Acc.ID LEFT OUTER JOIN Mas_Dia ON Trs_BillRate.DiaID = Mas_Dia.DiaID LEFT OUTER JOIN Mas_Exporter ON Trs_Bills.coycode = Mas_Exporter.ExpID LEFT OUTER JOIN Mas_Party ON Trs_Bills.party = Mas_Party.PID LEFT OUTER JOIN Mas_AccDes ON Trs_BillRate.Ades = Mas_AccDes.ID LEFT OUTER JOIN Mas_Count ON Trs_BillRate.Cntid = Mas_Count.CountID ON Mas_Size.SizeID = Trs_BillRate.Asiz LEFT OUTER JOIN Mas_Part ON Trs_BillRate.PanelID = Mas_Part.PartID LEFT OUTER JOIN Mas_Mill ON Trs_BillRate.MillID = Mas_Mill.MillID LEFT OUTER JOIN Mas_StyleDesc ON Trs_BillRate.StyleID = Mas_StyleDesc.StyleID LEFT OUTER JOIN Mas_Fabric ON Trs_BillRate.Fabid = Mas_Fabric.FabID LEFT OUTER JOIN Mas_JobWrkComp ON 
 Trs_BillRate.dept = Mas_JobWrkComp.Id LEFT OUTER JOIN Mas_Dept ON Mas_JobWrkComp.DeptId = Mas_Dept.DeptID LEFT OUTER JOIN Mas_Color ON Trs_BillRate.ColId = Mas_Color.ColID LEFT OUTER JOIN OrderMas AS OrderMas_1 ON Vue_BillGrn.OrdID = OrderMas_1.OrdId And Trs_BillRate.Atype=Trs_BillDeb2.Atype And Trs_BillRate.Ades=Trs_BillDeb2.Ades Left Outer join Mas_Component on Mas_Component.CompID = Trs_BillRate.Compid  LEFT OUTER JOIN Mas_User ON Mas_User.UserCode = Trs_Bills.PreparedBy LEFT OUTER JOIN Mas_Size Mas_Size1 ON Mas_Size1.SizeID = Trs_BillRate.SizeID where Trs_Bills.ID =(@ordid)' EXEC SP_EXECUTESQL @SQLSTR,N' @ordid nvarchar(200)', @ordid= @ordid END





