/**
 * The 28 report configs — SPEC-M6 §4 (frozen inventory; the contract test
 * pins slug↔service bijection + pack membership). Bound reports mirror their
 * register configs' filters/columns (ONE service, two screens — never fork).
 */
import type { ReportConfig } from './types'

const f = {
  dateRange: [
    { key: 'from', label: 'From', type: 'dateRange' as const },
    { key: 'to', label: 'To', type: 'dateRange' as const },
  ],
  party: { key: 'party', label: 'Party', type: 'party' as const, placeholder: 'Party code' },
  order: { key: 'order', label: 'Order', type: 'order' as const, placeholder: 'SO-1001' },
  godown: { key: 'godown', label: 'Godown', type: 'godown' as const, placeholder: 'Godown code' },
  itemType: {
    key: 'itemType', label: 'Item Type', type: 'select' as const,
    options: [
      { value: 'yarn', label: 'Yarn' }, { value: 'fabric', label: 'Fabric' },
      { value: 'accessory', label: 'Accessory' }, { value: 'pcs', label: 'Pcs' },
    ],
  },
  q: { key: 'q', label: 'Search', type: 'text' as const, placeholder: 'Order / buyer / style' },
}

export const REPORTS: ReportConfig[] = [
  // ================= ORDER PACK (5) =================
  {
    slug: 'order-register', title: 'Order Register', pack: 'order',
    description: 'All sales orders with buyer, style, value and status.',
    filters: [{ key: 'status', label: 'Status', type: 'select', options: [
      { value: 'open', label: 'Open' }, { value: 'in_progress', label: 'In Progress' },
      { value: 'completed', label: 'Completed' }, { value: 'cancelled', label: 'Cancelled' },
    ] }, ...f.dateRange, f.q],
    columns: [
      { name: 'orderNo', label: 'Order', mono: true },
      { name: 'buyer', label: 'Buyer' },
      { name: 'style', label: 'Style' },
      { name: 'orderDate', label: 'Date', format: 'date' },
      { name: 'deliveryDate', label: 'Delivery', format: 'date' },
      { name: 'totalPcs', label: 'Pcs', align: 'right', format: 'int' },
      { name: 'totalValue', label: 'Value', align: 'right', format: 'inr' },
      { name: 'status', label: 'Status', format: 'badge' },
    ],
    agentTools: ['list_orders'], askPrompt: 'Order register report',
  },
  {
    slug: 'inhand-orders', title: 'In-hand Orders', pack: 'order',
    description: 'Open orders with balance quantities to produce.',
    filters: [f.q],
    columns: [
      { name: 'orderNo', label: 'Order', mono: true },
      { name: 'buyer', label: 'Buyer' },
      { name: 'style', label: 'Style' },
      { name: 'orderDate', label: 'Date', format: 'date' },
      { name: 'deliveryDate', label: 'Delivery', format: 'date' },
      { name: 'totalPcs', label: 'Ordered', align: 'right', format: 'int' },
      { name: 'despatchedPcs', label: 'Despatched', align: 'right', format: 'int' },
      { name: 'pendingPcs', label: 'Pending', align: 'right', format: 'int' },
      { name: 'invoicedQty', label: 'Invoiced', align: 'right', format: 'int' },
      { name: 'status', label: 'Status', format: 'badge' },
    ],
    agentTools: ['list_inhand_orders'], askPrompt: 'In-hand orders report',
  },
  {
    slug: 'order-status-summary', title: 'Order Status Summary', pack: 'order',
    description: 'Per-order chain progress (n/15 stages), produced vs despatched, next stage.',
    filters: [{ key: 'status', label: 'Status', type: 'select', options: [
      { value: 'open', label: 'Open' }, { value: 'in_progress', label: 'In Progress' },
      { value: 'completed', label: 'Completed' },
    ] }, f.q],
    columns: [
      { name: 'orderNo', label: 'Order', mono: true },
      { name: 'buyer', label: 'Buyer' },
      { name: 'stages', label: 'Stages' },
      { name: 'nextStage', label: 'Next' },
      { name: 'ordered', label: 'Ordered', align: 'right', format: 'int' },
      { name: 'produced', label: 'Produced', align: 'right', format: 'int' },
      { name: 'despatched', label: 'Despatched', align: 'right', format: 'int' },
      { name: 'balance', label: 'Balance', align: 'right', format: 'int' },
      { name: 'deliveryDate', label: 'Delivery', format: 'date' },
    ],
    agentTools: ['get_order_status'], askPrompt: 'Order status summary report',
  },
  {
    slug: 'sample-status', title: 'Sample Status', pack: 'order',
    description: 'Sample development tracker: proto/photo/counter samples and approvals.',
    filters: [...f.dateRange, { key: 'status', label: 'Status', type: 'select', options: [
      { value: 'submitted', label: 'Submitted' }, { value: 'approved', label: 'Approved' },
      { value: 'rejected', label: 'Rejected' }, { value: 'closed', label: 'Closed' },
    ] }],
    columns: [
      { name: 'sampleNo', label: 'Sample', mono: true },
      { name: 'buyer', label: 'Buyer' },
      { name: 'style', label: 'Style' },
      { name: 'sampleType', label: 'Type' },
      { name: 'qty', label: 'Qty', align: 'right', format: 'int' },
      { name: 'sampledOn', label: 'Date', format: 'date' },
      { name: 'status', label: 'Status', format: 'badge' },
    ],
    agentTools: ['render_report'], askPrompt: 'Sample status report',
  },
  {
    slug: 'despatch-packing-summary', title: 'Despatch & Packing Summary', pack: 'order',
    description: 'Despatch rollup per order with cartons packed and despatch value.',
    filters: [...f.dateRange, f.order],
    columns: [
      { name: 'orderNo', label: 'Order', mono: true },
      { name: 'buyer', label: 'Buyer' },
      { name: 'dcs', label: 'DCs', align: 'right', format: 'int' },
      { name: 'pcs', label: 'Pcs', align: 'right', format: 'int' },
      { name: 'cartons', label: 'Cartons', align: 'right', format: 'int' },
      { name: 'value', label: 'Value', align: 'right', format: 'inr' },
      { name: 'lastDate', label: 'Last DC', format: 'date' },
    ],
    agentTools: ['list_despatches'], askPrompt: 'Despatch and packing summary',
  },

  // ================= PRODUCTION PACK (5) =================
  {
    slug: 'production-status', title: 'Production Status', pack: 'production',
    description: 'Production entries per order with qty, rework and wages.',
    filters: [...f.dateRange, f.order, f.q],
    columns: [
      { name: 'orderNo', label: 'Order', mono: true },
      { name: 'buyer', label: 'Buyer' },
      { name: 'dept', label: 'Dept' },
      { name: 'qty', label: 'Qty', align: 'right', format: 'int' },
      { name: 'reworkQty', label: 'Rework', align: 'right', format: 'int' },
      { name: 'jobworkQty', label: 'Jobwork', align: 'right', format: 'qty' },
      { name: 'amount', label: 'Amount', align: 'right', format: 'inr' },
      { name: 'shiftWages', label: 'Wages', align: 'right', format: 'inr' },
    ],
    agentTools: ['get_production_status'], askPrompt: 'Production status report',
  },
  {
    slug: 'daily-in-out', title: 'Daily In-Out', pack: 'production',
    description: 'Day-wise material in/out totals from the stock ledger.',
    filters: [...f.dateRange, f.godown, f.itemType],
    columns: [
      { name: 'docDate', label: 'Date', format: 'date' },
      { name: 'godown', label: 'Godown' },
      { name: 'txnType', label: 'Txn', format: 'badge' },
      { name: 'docNo', label: 'Doc', mono: true },
      { name: 'itemCode', label: 'Item', mono: true },
      { name: 'party', label: 'Party' },
      { name: 'inKgs', label: 'In Kgs', align: 'right', format: 'qty' },
      { name: 'outKgs', label: 'Out Kgs', align: 'right', format: 'qty' },
      { name: 'inPcs', label: 'In Pcs', align: 'right', format: 'int' },
      { name: 'outPcs', label: 'Out Pcs', align: 'right', format: 'int' },
    ],
    agentTools: ['get_daily_in_out'], askPrompt: 'Daily in-out report',
  },
  {
    slug: 'line-wip', title: 'Line WIP Summary', pack: 'production',
    description: 'Issued vs produced vs pending pieces per production line.',
    filters: [...f.dateRange, f.order],
    columns: [
      { name: 'line', label: 'Line', mono: true },
      { name: 'lineName', label: 'Name' },
      { name: 'issues', label: 'Issues', align: 'right', format: 'int' },
      { name: 'issued', label: 'Issued', align: 'right', format: 'int' },
      { name: 'produced', label: 'Produced', align: 'right', format: 'int' },
      { name: 'wip', label: 'WIP', align: 'right', format: 'int' },
    ],
    agentTools: ['get_line_status'], askPrompt: 'Line WIP report',
  },
  {
    slug: 'rejection-summary', title: 'Rejection Summary', pack: 'production',
    description: 'Rejections by department and type with scrap/rework/return split.',
    filters: [...f.dateRange, f.order, { key: 'status', label: 'Type', type: 'select', options: [
      { value: 'stitch_fault', label: 'Stitch' }, { value: 'size_fault', label: 'Size' },
      { value: 'fabric_fault', label: 'Fabric' }, { value: 'shade_fault', label: 'Shade' },
      { value: 'damage', label: 'Damage' }, { value: 'other', label: 'Other' },
    ] }],
    columns: [
      { name: 'dept', label: 'Dept' },
      { name: 'rejType', label: 'Type' },
      { name: 'count', label: 'Entries', align: 'right', format: 'int' },
      { name: 'qty', label: 'Qty', align: 'right', format: 'int' },
      { name: 'scrap', label: 'Scrap', align: 'right', format: 'int' },
      { name: 'rework', label: 'Rework', align: 'right', format: 'int' },
      { name: 'returned', label: 'Returned', align: 'right', format: 'int' },
    ],
    agentTools: ['render_report'], askPrompt: 'Rejection summary report',
  },
  {
    slug: 'operation-summary', title: 'Operation Summary', pack: 'production',
    description: 'Production rollup per department: entries, qty, value, wages.',
    filters: [...f.dateRange, f.order],
    columns: [
      { name: 'dept', label: 'Dept' },
      { name: 'entries', label: 'Entries', align: 'right', format: 'int' },
      { name: 'qty', label: 'Qty', align: 'right', format: 'int' },
      { name: 'amount', label: 'Amount', align: 'right', format: 'inr' },
      { name: 'wages', label: 'Wages', align: 'right', format: 'inr' },
      { name: 'rework', label: 'Rework', align: 'right', format: 'int' },
    ],
    agentTools: ['render_report'], askPrompt: 'Operation summary report',
  },

  // ================= INVENTORY PACK (5) =================
  {
    slug: 'stock-register', title: 'Stock Register', pack: 'inventory',
    description: 'Stock position by item and godown with valuation.',
    filters: [{ key: 'variant', label: 'View', type: 'select', options: [
      { value: 'general', label: 'General' }, { value: 'style', label: 'Style (pcs)' },
      { value: 'pcs', label: 'Pcs Detail' },
    ] }, f.godown, f.itemType],
    columns: [
      { name: 'itemType', label: 'Type' },
      { name: 'itemCode', label: 'Item', mono: true },
      { name: 'orderNo', label: 'Order', mono: true },
      { name: 'godown', label: 'Godown' },
      { name: 'bags', label: 'Bags', align: 'right', format: 'qty' },
      { name: 'kgs', label: 'Kgs', align: 'right', format: 'qty' },
      { name: 'mtrs', label: 'Mtrs', align: 'right', format: 'qty' },
      { name: 'pcs', label: 'Pcs', align: 'right', format: 'int' },
      { name: 'value', label: 'Value', align: 'right', format: 'inr' },
    ],
    agentTools: ['get_stock'], askPrompt: 'Stock register report',
  },
  {
    slug: 'current-stock', title: 'Current Stock', pack: 'inventory',
    description: 'Live current stock buckets with per-item rate and value.',
    filters: [f.itemType, f.godown],
    columns: [
      { name: 'itemCode', label: 'Item', mono: true },
      { name: 'itemType', label: 'Type' },
      { name: 'godown', label: 'Godown' },
      { name: 'bags', label: 'Bags', align: 'right', format: 'int' },
      { name: 'kgs', label: 'Kgs', align: 'right', format: 'qty' },
      { name: 'mtrs', label: 'Mtrs', align: 'right', format: 'qty' },
      { name: 'pcs', label: 'Pcs', align: 'right', format: 'int' },
      { name: 'rate', label: 'Rate', align: 'right', format: 'qty' },
      { name: 'value', label: 'Value', align: 'right', format: 'inr' },
    ],
    agentTools: ['get_stock'], askPrompt: 'Current stock report',
  },
  {
    slug: 'stock-ledger', title: 'Stock Ledger', pack: 'inventory',
    description: 'Every stock movement with in/out quantities and running balance.',
    filters: [...f.dateRange, f.godown, f.itemType],
    columns: [
      { name: 'docDate', label: 'Date', format: 'date' },
      { name: 'txnType', label: 'Txn', format: 'badge' },
      { name: 'docNo', label: 'Doc', mono: true },
      { name: 'itemCode', label: 'Item', mono: true },
      { name: 'itemType', label: 'Type' },
      { name: 'godown', label: 'Godown' },
      { name: 'party', label: 'Party' },
      { name: 'inKgs', label: 'In Kgs', align: 'right', format: 'qty' },
      { name: 'outKgs', label: 'Out Kgs', align: 'right', format: 'qty' },
      { name: 'inPcs', label: 'In Pcs', align: 'right', format: 'int' },
      { name: 'outPcs', label: 'Out Pcs', align: 'right', format: 'int' },
      { name: 'rate', label: 'Rate', align: 'right', format: 'qty' },
    ],
    agentTools: ['get_stock_ledger'], askPrompt: 'Stock ledger report',
  },
  {
    slug: 'lot-tracking', title: 'Lot Tracking', pack: 'inventory',
    description: 'Fabric/yarn lots with stock on hand per lot.',
    filters: [f.party, f.q],
    columns: [
      { name: 'lotNo', label: 'Lot', mono: true },
      { name: 'party', label: 'Party' },
      { name: 'kgs', label: 'Kgs', align: 'right', format: 'qty' },
      { name: 'mtrs', label: 'Mtrs', align: 'right', format: 'qty' },
      { name: 'pcs', label: 'Pcs', align: 'right', format: 'int' },
      { name: 'godowns', label: 'Godowns', align: 'right', format: 'int' },
    ],
    agentTools: ['list_lots'], askPrompt: 'Lot tracking report',
  },
  {
    slug: 'io-history', title: 'IO History', pack: 'inventory',
    description: 'Item movement history with running balance per item.',
    filters: [...f.dateRange, f.itemType, f.q],
    columns: [
      { name: 'docDate', label: 'Date', format: 'date' },
      { name: 'txnType', label: 'Txn', format: 'badge' },
      { name: 'docNo', label: 'Doc', mono: true },
      { name: 'itemCode', label: 'Item', mono: true },
      { name: 'godown', label: 'Godown' },
      { name: 'party', label: 'Party' },
      { name: 'inKgs', label: 'In', align: 'right', format: 'qty' },
      { name: 'outKgs', label: 'Out', align: 'right', format: 'qty' },
      { name: 'balKgs', label: 'Bal Kgs', align: 'right', format: 'qty' },
      { name: 'inPcs', label: 'In Pcs', align: 'right', format: 'int' },
      { name: 'outPcs', label: 'Out Pcs', align: 'right', format: 'int' },
      { name: 'balPcs', label: 'Bal Pcs', align: 'right', format: 'int' },
    ],
    agentTools: ['list_io_history'], askPrompt: 'IO history report',
  },

  // ================= ACCOUNTS PACK (6) =================
  {
    slug: 'bills-register', title: 'Bills Register', pack: 'accounts',
    description: 'Invoice day-book with deductions, collections and outstanding.',
    filters: [...f.dateRange, f.party, { key: 'status', label: 'Status', type: 'select', options: [
      { value: 'draft', label: 'Draft' }, { value: 'issued', label: 'Issued' },
      { value: 'paid', label: 'Paid' }, { value: 'cancelled', label: 'Cancelled' },
    ] }],
    columns: [
      { name: 'date', label: 'Date', format: 'date' },
      { name: 'docNo', label: 'Bill', mono: true },
      { name: 'party', label: 'Party' },
      { name: 'docType', label: 'Type', format: 'badge' },
      { name: 'billAmount', label: 'Billed', align: 'right', format: 'inr' },
      { name: 'deduction', label: 'Deduction', align: 'right', format: 'inr' },
      { name: 'collected', label: 'Collected', align: 'right', format: 'inr' },
      { name: 'status', label: 'Status', format: 'badge' },
    ],
    agentTools: ['get_bills_register'], askPrompt: 'Bills register report',
  },
  {
    slug: 'supplier-bills', title: 'Supplier Bills', pack: 'accounts',
    description: 'GRN day-book with bill-pass state per supplier.',
    filters: [...f.dateRange, f.party, { key: 'status', label: 'Type', type: 'select', options: [
      { value: 'purchase', label: 'Purchase' }, { value: 'process', label: 'Process' },
      { value: 'direct_receipt', label: 'Direct' }, { value: 'process_return', label: 'Process Return' },
      { value: 'sales_return', label: 'Sales Return' },
    ] }],
    columns: [
      { name: 'grnNo', label: 'GRN', mono: true },
      { name: 'grnType', label: 'Type', format: 'badge' },
      { name: 'party', label: 'Supplier' },
      { name: 'poNo', label: 'PO', mono: true },
      { name: 'grnDate', label: 'Date', format: 'date' },
      { name: 'totalQty', label: 'Qty', align: 'right', format: 'qty' },
      { name: 'totalValue', label: 'Value', align: 'right', format: 'inr' },
      { name: 'billPass', label: 'Bill Pass', format: 'badge' },
    ],
    agentTools: ['list_supplier_bills'], askPrompt: 'Supplier bills report',
  },
  {
    slug: 'party-ledger', title: 'Party Ledger', pack: 'accounts',
    description: 'Bill/receipt ledger per party with running balance.',
    filters: [f.party, f.q],
    columns: [
      { name: 'code', label: 'Code', mono: true },
      { name: 'party', label: 'Party' },
      { name: 'opening', label: 'Opening', align: 'right', format: 'inr' },
      { name: 'billed', label: 'Billed', align: 'right', format: 'inr' },
      { name: 'debit', label: 'Debit', align: 'right', format: 'inr' },
      { name: 'journals', label: 'Journals', align: 'right', format: 'inr' },
      { name: 'received', label: 'Received', align: 'right', format: 'inr' },
      { name: 'paid', label: 'Paid', align: 'right', format: 'inr' },
      { name: 'balance', label: 'Balance', align: 'right', format: 'inr' },
    ],
    agentTools: ['get_party_ledger'], askPrompt: 'Party ledger report',
  },
  {
    slug: 'party-balance', title: 'Party Balance', pack: 'accounts',
    description: 'Pending purchase positions per party.',
    filters: [f.party, f.q],
    columns: [
      { name: 'code', label: 'Code', mono: true },
      { name: 'party', label: 'Party' },
      { name: 'poCount', label: 'POs', align: 'right', format: 'int' },
      { name: 'orderedQty', label: 'Ordered', align: 'right', format: 'qty' },
      { name: 'receivedQty', label: 'Received', align: 'right', format: 'qty' },
      { name: 'pendingQty', label: 'Pending Qty', align: 'right', format: 'qty' },
      { name: 'pendingValue', label: 'Pending Value', align: 'right', format: 'inr' },
    ],
    agentTools: ['get_party_ledger'], askPrompt: 'Party balance report',
  },
  {
    slug: 'outstanding-summary', title: 'Outstanding Summary', pack: 'accounts',
    description: 'AR/AP outstanding per party with aging buckets (0-15/16-30/31-60/60+).',
    filters: [...f.dateRange, f.party],
    columns: [
      { name: 'party', label: 'Party' },
      { name: 'type', label: 'Type' },
      { name: 'billed', label: 'Billed', align: 'right', format: 'inr' },
      { name: 'settled', label: 'Settled', align: 'right', format: 'inr' },
      { name: 'outstanding', label: 'Outstanding', align: 'right', format: 'inr' },
      { name: 'b0', label: '0-15', align: 'right', format: 'inr' },
      { name: 'b1', label: '16-30', align: 'right', format: 'inr' },
      { name: 'b2', label: '31-60', align: 'right', format: 'inr' },
      { name: 'b3', label: '60+', align: 'right', format: 'inr' },
    ],
    agentTools: ['render_report'], askPrompt: 'Outstanding summary report',
  },
  {
    slug: 'gst-summary', title: 'GST Summary', pack: 'accounts',
    description: 'Tax rollup by month and rate: taxable, CGST, SGST, IGST.',
    filters: [...f.dateRange],
    columns: [
      { name: 'month', label: 'Month', mono: true },
      { name: 'rate', label: 'Rate %', align: 'right', format: 'qty' },
      { name: 'taxType', label: 'Tax' },
      { name: 'invoices', label: 'Invoices', align: 'right', format: 'int' },
      { name: 'taxable', label: 'Taxable', align: 'right', format: 'inr' },
      { name: 'cgst', label: 'CGST', align: 'right', format: 'inr' },
      { name: 'sgst', label: 'SGST', align: 'right', format: 'inr' },
      { name: 'igst', label: 'IGST', align: 'right', format: 'inr' },
      { name: 'total', label: 'Total', align: 'right', format: 'inr' },
    ],
    agentTools: ['render_report'], askPrompt: 'GST summary report',
  },

  // ================= COSTING & HR PACK (5) =================
  {
    slug: 'budget-vs-actual', title: 'Budget vs Actual', pack: 'costing-hr',
    description: 'Budget lines against actual consumption per order.',
    filters: [f.order],
    columns: [
      { name: 'orderNo', label: 'Order', mono: true },
      { name: 'buyer', label: 'Buyer' },
      { name: 'budgeted', label: 'Budgeted', align: 'right', format: 'inr' },
      { name: 'poValue', label: 'PO Value', align: 'right', format: 'inr' },
      { name: 'prodCost', label: 'Prod Cost', align: 'right', format: 'inr' },
      { name: 'actual', label: 'Actual', align: 'right', format: 'inr' },
      { name: 'variance', label: 'Variance', align: 'right', format: 'inr' },
    ],
    agentTools: ['get_budget_vs_actual'], askPrompt: 'Budget vs actual report',
  },
  {
    slug: 'daily-unit-pnl', title: 'Daily Unit P&L', pack: 'costing-hr',
    description: 'Per department per day: produced value, wages, margin. Expenses are period-level.',
    filters: [...f.dateRange, f.order],
    columns: [
      { name: 'dept', label: 'Dept' },
      { name: 'date', label: 'Date', format: 'date' },
      { name: 'qty', label: 'Qty', align: 'right', format: 'int' },
      { name: 'produced', label: 'Produced Value', align: 'right', format: 'inr' },
      { name: 'wages', label: 'Wages', align: 'right', format: 'inr' },
      { name: 'margin', label: 'Margin', align: 'right', format: 'inr' },
    ],
    agentTools: ['render_report'], askPrompt: 'Daily unit P&L report',
  },
  {
    slug: 'expenses-summary', title: 'Expenses Summary', pack: 'costing-hr',
    description: 'Expense book by category with order linkage.',
    filters: [...f.dateRange, f.order, { key: 'status', label: 'Category', type: 'select', options: [
      { value: 'fixed', label: 'Fixed' }, { value: 'stylewise', label: 'Stylewise' },
      { value: 'general', label: 'General' }, { value: 'transport', label: 'Transport' },
      { value: 'other', label: 'Other' },
    ] }],
    columns: [
      { name: 'expNo', label: 'Exp No', mono: true },
      { name: 'date', label: 'Date', format: 'date' },
      { name: 'category', label: 'Category' },
      { name: 'order', label: 'Order', mono: true },
      { name: 'amount', label: 'Amount', align: 'right', format: 'inr' },
      { name: 'status', label: 'Status', format: 'badge' },
    ],
    agentTools: ['render_report'], askPrompt: 'Expenses summary report',
  },
  {
    slug: 'production-wages', title: 'Wages Summary', pack: 'costing-hr',
    description: 'Operator production wages rollup.',
    filters: [...f.dateRange, f.order, f.q],
    columns: [
      { name: 'operator', label: 'Operator' },
      { name: 'code', label: 'Code', mono: true },
      { name: 'dept', label: 'Dept' },
      { name: 'orders', label: 'Orders', align: 'right', format: 'int' },
      { name: 'entries', label: 'Entries', align: 'right', format: 'int' },
      { name: 'qty', label: 'Qty', align: 'right', format: 'int' },
      { name: 'rate', label: 'Rate', align: 'right', format: 'inr' },
      { name: 'amount', label: 'Amount', align: 'right', format: 'inr' },
    ],
    agentTools: ['get_production_wages'], askPrompt: 'Wages summary report',
  },
  {
    slug: 'cost-sheet-summary', title: 'Cost Sheet Summary', pack: 'costing-hr',
    description: 'Cost sheet versions per order with margin.',
    filters: [f.order],
    columns: [
      { name: 'orderNo', label: 'Order', mono: true },
      { name: 'buyer', label: 'Buyer' },
      { name: 'version', label: 'Ver', align: 'right', format: 'int' },
      { name: 'totalCost', label: 'Total Cost', align: 'right', format: 'inr' },
      { name: 'sellingPrice', label: 'Selling Price', align: 'right', format: 'inr' },
      { name: 'marginPct', label: 'Margin %', align: 'right', format: 'qty' },
    ],
    agentTools: ['render_report'], askPrompt: 'Cost sheet summary report',
  },

  // ================= QUALITY PACK (2) =================
  {
    slug: 'lab-tests', title: 'Lab Test Report', pack: 'quality',
    description: 'QCDATA log with pass/fail results per item type.',
    filters: [...f.dateRange, f.itemType, { key: 'status', label: 'Result', type: 'select', options: [
      { value: 'pending', label: 'Pending' }, { value: 'pass', label: 'Pass' },
      { value: 'fail', label: 'Fail' }, { value: 'conditional', label: 'Conditional' },
    ] }],
    columns: [
      { name: 'testNo', label: 'Test', mono: true },
      { name: 'itemType', label: 'Item Type' },
      { name: 'testType', label: 'Test' },
      { name: 'result', label: 'Result', format: 'badge' },
      { name: 'testedOn', label: 'Date', format: 'date' },
      { name: 'testedBy', label: 'By' },
    ],
    agentTools: ['render_report'], askPrompt: 'Lab test report',
  },
  {
    slug: 'approval-audit', title: 'Approval Audit Trail', pack: 'quality',
    description: 'Every approval decision with timestamps and references.',
    filters: [{ key: 'status', label: 'Status', type: 'select', options: [
      { value: 'pending', label: 'Pending' }, { value: 'approved', label: 'Approved' },
      { value: 'rejected', label: 'Rejected' },
    ] }, ...f.dateRange],
    columns: [
      { name: 'createdAt', label: 'At', format: 'date' },
      { name: 'entity', label: 'Kind', format: 'badge' },
      { name: 'entityId', label: 'Ref', mono: true },
      { name: 'step', label: 'Step', align: 'right', format: 'int' },
      { name: 'requestedBy', label: 'By' },
      { name: 'approvedBy', label: 'Decided By' },
      { name: 'approvedAt', label: 'Decided At', format: 'date' },
      { name: 'status', label: 'Status', format: 'badge' },
    ],
    agentTools: ['get_approval_audit'], askPrompt: 'Approval audit report',
  },
]

export function getReportConfig(slug: string): ReportConfig | undefined {
  return REPORTS.find((r) => r.slug === slug)
}
