/*;=============================================   
; Author           :  Global Software's    
; Create date      :  14/11/2025    
; Create By        :  ASLAM  
; Description      :  QUERY
; Change Person    :  ASLAM
; Last Change Date :  14/11/2025 10.05 AM 
; =============================================  */  
CREATE VIEW Vue_YarnProgBalDetailYarnOnly_N AS /* Process Type Are added by seetha on 27.08.2011 For Program Balance Report */ 

SELECT 'Req' AS Type, Pro_ReqYarn.OrdId, Mas_Dept.DeptID, Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Count.CountName, ISNULL(Mas_Color.ColorDesc, '') AS ColorDesc, SUM(Pro_ReqYarn.ReqKgs) AS ReqKgs, 0 AS PoKgs, 0 AS RecKgs, 0 AS ProDelKgs, 0 AS ProRetKgs, 0 AS PurRetKgs, 0 AS TranInKgs, 0 AS TranOutKgs,'P'as processtype,0 as opening,isnull(Mas_Count.CountId,0) as CountId,IsNull(Mas_Color.ColId,0) as ColId  FROM Pro_ReqYarn INNER JOIN Mas_Dept ON Pro_ReqYarn
.DeptId = Mas_Dept.DeptID INNER JOIN Mas_Count ON Pro_ReqYarn.CountId = Mas_Count.CountID LEFT OUTER JOIN Mas_Color ON Pro_ReqYarn.ColId = Mas_Color.ColID GROUP BY Pro_ReqYarn.OrdId, Mas_Dept.DeptID, Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Count.CountName, ISNULL(Mas_Color.ColorDesc, '') ,isnull(Mas_Count.CountId,0) ,IsNull(Mas_Color.ColId,0)

UNION ALL  

SELECT 'PO' AS Type, Trs_Po2.OrdID, Mas_Dept.DeptID, Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Count.CountName, ISNULL(Mas_Color.ColorDesc, '') AS ColorDesc, 0 AS ReqKgs, SUM(Trs_Po2.PoQty-cancelkgs) AS PoQty, 0 AS RecKgs, 0 AS ProDelKgs, 0 AS ProRetKgs, 0 AS PurRetKgs, 0 AS TranInKgs, 0 AS TranOutKgs,'P'as processtype,0 as opening,isnull(Mas_Count.CountId,0) as CountId,IsNull(Mas_Color.ColId,0) as ColId  FROM Trs_Po2 INNER JOIN Trs_Po1 ON Trs_Po2.ID = Trs_Po1.ID INNER JOIN Mas_Dept ON Trs_Po1.Dept = Mas_Dept.DeptID INNER JOIN Mas_Count ON Trs_Po2.CntId = Mas_Count.CountID LEFT OUTER JOIN Mas_Color ON Trs_Po2.ClrId = Mas_Color.ColID WHERE Mas_Dept.OutputType = 'Y' GROUP BY Trs_Po2.OrdID, Mas_Dept.DeptID, Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Count.CountName, ISNULL(Mas_Color.ColorDesc, '') ,isnull(Mas_Count.CountId,0) ,IsNull(Mas_Color.ColId,0) 
UNION ALL 

SELECT 'Grn' AS Type, Trs_Grn2.OrdID, Mas_Dept.DeptID, Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Count.CountName, ISNULL(Mas_Color.ColorDesc, '') AS ColorDesc, 0 AS ReqKgs, 0 AS PoKgs, SUM(Trs_GRN2.RecKgs) AS RecKgs, 0 AS ProDelKgs,
 0 AS ProRetKgs, 0 AS PurRetKgs, 0 AS TranInKgs, 0 AS TranOutKgs,Isnull(Trs_Grn1.processtype,'P')processtype,0 as opening,isnull(Mas_Count.CountId,0) as CountId,IsNull(Mas_Color.ColId,0) as ColId FROM Trs_Grn1 INNER JOIN Trs_GRN2 ON Trs_Grn1.ID = Trs_GRN2.ID INNER JOIN StockTable ON Trs_GRN2.StockID = StockTable.StockID INNER JOIN Mas_Dept ON Trs_Grn1.Dept = Mas_Dept.DeptID LEFT OUTER JOIN Mas_Color ON StockTable.ColID = Mas_Color.ColID INNER JOIN Mas_Count ON StockTable.CntID = Mas_Count.CountID WHERE Mas_Dept.OutputType = 'Y' AND Trs_Grn1.GRNType = 'Purchase' GROUP BY Trs_Grn2.OrdID, Mas_Dept.DeptID, Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Count.CountName, ISNULL(Mas_Color.ColorDesc, '') ,Isnull(Trs_Grn1.processtype,'P') ,isnull(Mas_Count.CountId,0) ,IsNull(Mas_Color.ColId,0)
 UNION ALL  
 SELECT 'Trans' AS Type, Trs_Del2.TranOrdID AS OrdID, Mas_Dept.DeptID, Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Count.CountName, ISNULL(Mas_Color.ColorDesc, '') AS ColorDesc, 0 AS ReqKgs, 0 AS PoKgs, 0 AS RecKgs, 0 AS ProDelKgs, 0 AS ProRetKgs, 0 AS PurRetKgs, SUM(Trs_Del2.Kg) AS TranInKgs, 0 AS TranOutKgs,Isnull(Trs_Del1.processtype,'P')processtype,0 as opening,isnull(Mas_Count.CountId,0) as CountId,IsNull(Mas_Color.ColId,0) as ColId FROM StockTable INNER JOIN Mas_Count ON StockTable.CntID = Mas_Count.CountID INNER JOIN Trs_Del2 ON StockTable.StockID = Trs_Del2.StockID INNER JOIN Trs_Del1 ON Trs_Del2.ID = Trs_Del1.ID INNER JOIN Mas_Dept ON Trs_Del1.Prs_Dept = Mas_Dept.DeptID LEFT OUTER JOIN Mas_Color ON StockTable.ColID = Mas_Color.ColID WHERE Mas_Dept.OutputType = 'Y' AND Trs_Del1.TrType = 3 GROUP BY Trs_Del2.TranOrdID, Mas_Dept.DeptID, Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Count.CountName, ISNULL(Mas_Color.ColorDesc, '') ,Isnull(Trs_Del1.processtype,'P') ,isnull(Mas_Count.CountId,0) ,IsNull(Mas_Color.ColId,0)
 
 UNION ALL 
 
 SELECT 'Open' AS Type, Trs_Opening.OrdID, Mas_Dept.DeptID, Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Count.CountName, ISNULL(Mas_Color.ColorDesc, '') AS ColorDesc, 0 AS ReqKgs, 0 AS PoKgs,0 AS RecKgs, 
0 AS ProDelKgs, 0 AS ProRetKgs, 0 AS PurRetKgs, 0 AS TranInKgs, 0 AS TranOutKgs,'P' as processtype, SUM(Trs_Opening.Kgs) as opening,isnull(Mas_Count.CountId,0) as CountId,IsNull(Mas_Color.ColId,0) as ColId FROM Trs_Opening INNER JOIN StockTable ON Trs_Opening.StockID = StockTable.StockID INNER JOIN Mas_Dept ON Trs_Opening.Dept 
= Mas_Dept.DeptID LEFT OUTER JOIN Mas_Count ON StockTable.CntID = Mas_Count.CountID LEFT OUTER JOIN Mas_Color ON StockTable.ColID = Mas_Color.ColID WHERE Mas_Dept.OutputType = 'Y' GROUP BY Trs_Opening.OrdID, Mas_Dept.DeptID, Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Count.CountName, ISNULL(Mas_Color.ColorDesc, '') ,isnull(Mas_Count.CountId,0) ,IsNull(Mas_Color.ColId,0)
UNION ALL 
SELECT 'ProDel' AS Type, Trs_Del2.OrdID, Mas_Dept.DeptID, Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Count.CountName, ISNULL(Mas_Color.ColorDesc, '') AS ColorDesc, 0 AS ReqKgs, 0 AS PoKgs, 0 AS RecKgs, SUM(Trs_Del2.Kg) AS ProDelKgs, 0 AS ProRetKgs, 0 AS PurRetKgs, 0 AS TranInKgs, 0 AS TranOutKgs,Isnull(Trs_Del1.processtype,'P')processtype,0 as opening,isnull(Mas_Count.CountId,0) as CountId,IsNull(Mas_Color.ColId,0) as ColId FROM StockTable INNER JOIN Mas_Count ON StockTable.CntID = Mas_Count.CountID INNER JOIN Trs_Del2 ON StockTable.StockID = Trs_Del2.StockID INNER JOIN Trs_Del1 ON Trs_Del2.ID = Trs_Del1.ID INNER JOIN Mas_Dept ON StockTable.Dept = Mas_Dept.DeptID LEFT OUTER JOIN Mas_Color ON StockTable.ColID = Mas_Color.ColID WHERE Mas_Dept.InputType = 'Y' AND Trs_Del1.TrType = 1   GROUP BY Trs_Del2.OrdID, Mas_Dept.DeptID, Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Count.CountName, ISNULL(Mas_Color.ColorDesc, '') ,Isnull(Trs_Del1.processtype,'P') ,isnull(Mas_Count.CountId,0) ,IsNull(Mas_Color.ColId,0)

UNION ALL  

SELECT 'Sales' AS Type, Trs_Del2.OrdID, Mas_Dept.DeptID, Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Count.CountName, ISNULL(Mas_Color.ColorDesc, '') AS ColorDesc, 0 AS ReqKgs, 0 AS PoKgs, 0 AS RecKgs, SUM(Trs_Del2.Kg) AS ProDelKgs, 0 AS ProRetKgs, 0 AS PurRetKgs, 0 AS TranInKgs, 0 AS TranOutKgs,'P' as processtype,0 as opening ,isnull(Mas_Count.CountId,0) as CountId,IsNull(Mas_Color.ColId,0) as ColId  FROM StockTable INNER JOIN Mas_Count ON StockTable.CntID = Mas_Count.CountID INNER JOIN Trs_Del2 ON StockTable.StockID = Trs_Del2.StockID INNER JOIN Trs_Del1 ON Trs_Del2.ID = Trs_Del1.ID INNER JOIN Mas_Dept ON StockTable.Dept = Mas_Dept
.DeptID LEFT OUTER JOIN Mas_Color ON StockTable.ColID = Mas_Color.ColID WHERE Mas_Dept.InputType = 'Y' AND Trs_Del1.TrType = 2    and Prs_Dept =-1 GROUP BY Trs_Del2.OrdID, Mas_Dept.DeptID, Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Count.CountName, ISNULL(Mas_Color.ColorDesc, '') ,Isnull(Trs_Del1.processtype,'P') ,isnull(Mas_Count.CountId,0) ,IsNull(Mas_Color.ColId,0)
UNION ALL 
SELECT 'Trans' AS Type, Trs_Del2.OrdID, Mas_Dept.DeptID, Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Count.CountName, ISNULL(Mas_Color.ColorDesc, '') AS ColorDesc, 0 AS ReqKgs, 0 AS PoKgs,
 0 AS RecKgs, 0 AS ProDelKgs, 0 AS ProRetKgs, 0 AS PurRetKgs, 0 AS TranInKgs, SUM(Trs_Del2.Kg) AS TranOutKgs,Isnull(Trs_Del1.processtype,'P')processtype,0 as opening,isnull(Mas_Count.CountId,0) as CountId,IsNull(Mas_Color.ColId,0) as ColId  FROM Trs_Del1 INNER JOIN Trs_Del2 ON Trs_Del1.ID = Trs_Del2.ID INNER JOIN StockTable ON StockTable.StockID = Trs_Del2.StockID LEFT OUTER JOIN Mas_Count ON StockTable.CntID = Mas_Count.CountID LEFT OUTER JOIN  Mas_Dept ON Trs_Del1.Prs_Dept = Mas_Dept.DeptID LEFT OUTER JOIN Mas_Color ON StockTable.ColID = Mas_Color.ColID WHERE  Mas_Dept.OutputType = 'Y' AND Trs_Del1.TrType = 3 GROUP BY Trs_Del2.OrdID, Mas_Dept.DeptID, Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Count.CountName, ISNULL(Mas_Color.ColorDesc, '') ,Isnull(Trs_Del1.processtype,'P')  ,isnull(Mas_Count.CountId,0) ,IsNull(Mas_Color.ColId,0)
 UNION ALL  
 SELECT 'ProRet' AS Type, Trs_Grn2.OrdID, Mas_Dept.DeptID, Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Count.CountName, ISNULL(Mas_Color.ColorDesc, '') AS ColorDesc, 0 AS ReqKgs, 0 AS PoKgs, 0 AS RecKgs,0 AS ProDelKgs, SUM(Trs_GRN2.RecKgs) AS ProRetKgs, 0 AS PurRetKgs, 0 AS TranInKgs, 0 AS TranOutKgs
,Isnull(Trs_Grn1.processtype,'P')processtype,0 as opening,isnull(Mas_Count.CountId,0) as CountId,IsNull(Mas_Color.ColId,0) as ColId  FROM Trs_Grn1 INNER JOIN Trs_GRN2  ON Trs_Grn1.ID = Trs_GRN2.ID INNER JOIN StockTable ON Trs_GRN2.StockID = StockTable.StockID INNER JOIN Mas_Dept ON StockTable.Dept = Mas_Dept.DeptID LEFT OUTER JOIN Mas_Color ON StockTable.ColID = Mas_Color.ColID INNER JOIN Mas_Count ON StockTable.CntID = Mas_Count.CountID WHERE Mas_Dept.InputType = 'Y' AND Trs_Grn1.GRNType In ( 'Process Return','Sales Return') GROUP BY StockTable.StockID, Trs_Grn2.OrdID, Mas_Dept
.DeptID, Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Count.CountName, ISNULL(Mas_Color.ColorDesc, ''),Isnull(Trs_Grn1.processtype,'P') ,Isnull(Trs_Grn1.processtype,'P')  ,isnull(Mas_Count.CountId,0) ,IsNull(Mas_Color.ColId,0)
UNION ALL  
SELECT 'PurRet' AS Type, Trs_Del2.OrdID, Mas_Dept.DeptID, Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Count.CountName, ISNULL(Mas_Color.ColorDesc, '') AS ColorDesc, 0 AS ReqKgs, 0 AS PoKgs, 0 AS RecKgs, 0 AS ProDelKgs, 0 AS ProRetKgs, SUM(Trs_Del2.Kg) AS PurRetKgs, 0 AS TranInKgs, 0 AS TranOutKgs,Isnull(Trs_Del1.processtype,'P')processtype,0 as opening,isnull(Mas_Count.CountId,0) as CountId,IsNull(Mas_Color.ColId,0) as ColId  FROM StockTable INNER JOIN Mas_Count ON StockTable.CntID = Mas_Count.CountID INNER JOIN Trs_Del2 ON StockTable.StockID = Trs_Del2.StockID INNER JOIN Trs_Del1 ON Trs_Del2.ID = Trs_Del1.ID INNER JOIN Mas_Dept ON Trs_Del1.Prs_Dept = Mas_Dept.DeptID LEFT OUTER JOIN Mas_Color ON StockTable.ColID = Mas_Color.ColID WHERE Mas_Dept.OutputType = 'Y' AND Trs_Del1.TrType = 4 GROUP BY Trs_Del2.OrdID, Mas_Dept.DeptID, Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Count.CountName, ISNULL(Mas_Color.ColorDesc, '') ,Isnull(Trs_Del1.processtype,'P') ,isnull(Mas_Count.CountId,0) ,IsNull(Mas_Color.ColId,0)
UNION ALL 
SELECT 'Short' AS Type, Trs_shortage.OrdID, Mas_Dept.DeptID, Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Count.CountName, ISNULL(Mas_Color.ColorDesc, '') AS ColorDesc, isnull(sum(shortkgs),0) AS ReqKgs, 
0 AS PoKgs, 0 AS RecKgs, 0 AS ProDelKgs, 0 AS ProRetKgs, 0 AS PurRetKgs, 0 AS TranInKgs, 0 AS TranOutKgs,'P' as processtype,0 as opening,isnull(Mas_Count.CountId,0) as CountId,IsNull(Mas_Color.ColId,0) as ColId  FROM trs_shortage INNER JOIN Mas_Count ON trs_shortage.CntID = Mas_Count.CountID INNER JOIN Mas_Dept ON trs_shortage.Dept = Mas_Dept.DeptID LEFT OUTER JOIN Mas_Color ON trs_shortage.ColID = Mas_Color.ColID WHERE Mas_Dept.OutputType = 'Y' GROUP BY Trs_shortage.OrdID, Mas_Dept.DeptID, Mas_Dept.Deptname, Mas_Dept.OrderSno, Mas_Count.CountName, ISNULL(Mas_Color.ColorDesc, '') ,isnull(Mas_Count.CountId,0) ,IsNull(Mas_Color.ColId,0)