/*                  
;=============================================                  
; Author  :  Global Software's                  
; Create date  :  01/Nov/2019                  
; Create By  :  ASLAM                  
; Description  :  Stored Procedure for Posting the Production Details for commando cloud
; Change Person  :  ASLAM                
; Last Change Date :  26/May/2021 11.20 AM                  
; =============================================   */ 
CREATE VIEW Vue_TrsDc AS 

SELECT 'DC' AS TrType, Case when MaS_Dept.RecMethod ='O' then TRs_del2.OrdwiseClose else Trs_Del1.Clos end as Clos, Trs_Del1.Coycode, Trs_Del2.OrdId, Trs_Del1.DocNo AS DcNo, Trs_Del1.Finyear, Trs_Del1.Dt AS DcDate, case Trs_Del1.PartyUnit when 'U' then   Mas_Exporter.ExporterName + '('+mas_exporter_1.ExporterName+ ')'  else Mas_Party.Pname end as Pname,Trs_Del1.Party as PID,  Mas_Dept.Deptname, Mas_Dept.DeptID, Trs_Del2.StockID, Trs_Del2.BgRl, Trs_Del2.Kg, Trs_Del2.mtr, Trs_Del1.ProcessType,Isnull(Trs_Del1.PartyUnit,'P')as PartyUnit, Trs_Del1.DyeColId,Trs_del1.DesignId, TrType As TransType,Trs_Del1.ID,'N' as MultiGRN,Trs_Del1.Remark ,mas_exporter_1.ExporterName as Name, mas_exporter_1.IsUnit as unit,IsNull(SubPrsId,0) as SubPrsID FROM  Trs_Del1 INNER JOIN Trs_Del2 ON Trs_Del1.ID = Trs_Del2.ID INNER JOIN Mas_Dept ON Trs_Del1.Prs_Dept = Mas_Dept.DeptID LEFT OUTER JOIN Mas_Party ON Trs_Del1.Party = Mas_Party.PID LEFT OUTER JOIN Mas_Exporter ON Trs_Del1.Party = Mas_Exporter.ExpID left outer join Mas_Exporter as mas_exporter_1 on mas_exporter_1.ExpID=Trs_Del1.Coycode  WHERE (Trs_Del1.TrType IN (1, 7, 10, 11, 12))   

UNION ALL /* External GRN -> Previous GRN IS Taken as DC for NEXT PROCESS.*/  SELECT 'DC' AS TrType, Case when MaS_Dept.RecMethod ='O' then Trs_MultiPrs_Grn3.OrderwiseClose else Trs_MultiPrs_Grn2.DCClose end as Clos,Trs_MultiPrs_Grn1.Coycode, Trs_MultiPrs_Grn3.OrdId, Trs_MultiPrs_Grn1.DocNo AS DcNo, Trs_MultiPrs_Grn1.Finyear, Trs_MultiPrs_Grn1.GrnDate AS DcDate, Mas_Party.Pname as Pname,Trs_MultiPrs_Grn2.
PartyID as PID, Mas_Dept.Deptname, Mas_Dept.DeptID, Trs_MultiPrs_Grn3.StockID, Trs_MultiPrs_Grn3.DCBag as BgRl, Trs_MultiPrs_Grn3.DCKgs as Kg, Trs_MultiPrs_Grn3.DCMtr mtr, Trs_MultiPrs_Grn1.ProcessType,'P' as PartyUnit, 0 as DyeColId, 0 as DesignId ,1 As 
TransType,Trs_MultiPrs_Grn1.ID,'Y' as MultiGRN,'' As Remark,''as name,0 as unit,IsNull(Trs_MultiPrs_Grn2.SubPrsId,0) as SubPrsID  FROM  Trs_MultiPrs_Grn1 INNER JOIN Trs_MultiPrs_Grn2 ON Trs_MultiPrs_Grn1.ID = Trs_MultiPrs_Grn2.ID INNER JOIN Trs_MultiPrs_Grn3 ON Trs_MultiPrs_Grn1.ID = Trs_MultiPrs_Grn3.ID
 and Trs_MultiPrs_Grn2.DeptID = Trs_MultiPrs_Grn3.DeptID INNER JOIN Mas_Dept ON Trs_MultiPrs_Grn2.DeptID = Mas_Dept.DeptID LEFT OUTER JOIN Mas_Party ON Trs_MultiPrs_Grn2.PartyID = Mas_Party.PID LEFT OUTER JOIN Mas_Exporter ON Trs_MultiPrs_Grn2.PartyID = Mas_Exporter.ExpID  WHERE Trs_MultiPrs_Grn2.OurDCID = 0 /*Comment Break*/  


UNION ALL SELECT'RET' AS TrType, '' AS Expr1, Trs_Del1_3.Coycode, Trs_Del2_3.OrdId, Trs_Del1_3.DocNo AS DcNo, Trs_Del1_3.Finyear AS DcFinyear,Trs_Del1_3.Dt AS DcDate,case Trs_Del1_3.PartyUnit when 'U' then  Mas_Exporter.ExporterName else Mas_Party_1.Pname end as Pname,Trs_Del1_3.Party as PID, Mas_Dept_3.Deptname, Mas_Dept_3.DeptID, Trs_Del2_3.StockID, Trs_Del2_3.BgRl, Trs_Del2_3.Kg, Trs_Del2_3.mtr, '' AS Expr2, Trs_Del1_3.PartyUnit,
Trs_Del1_3.DyeColId,Trs_Del1_3.DesignId , TrType As TransType,Trs_Del1_3.id,'N' as MultiGRN,'' As Remark,'' as name,0 as unit,isNull(Trs_Del1_3.SubPrsId,0) as SubPrsID FROM Trs_Del1 AS Trs_Del1_3 INNER JOIN Trs_Del2 AS Trs_Del2_3 ON Trs_Del1_3.ID = Trs_Del2_3.ID INNER JOIN Mas_Dept AS Mas_Dept_3 
ON Trs_Del1_3.Prs_Dept =  Mas_Dept_3.DeptID LEFT OUTER JOIN Mas_Party AS Mas_Party_1 ON Trs_Del1_3.Party = Mas_Party_1.PID LEFT OUTER JOIN Mas_Exporter ON Trs_Del1_3.Party = Mas_Exporter.ExpID WHERE     (Trs_Del1_3.TrType IN (4, 6)) /*Comment Break*/   UNION ALL SELECT     'TRANS' AS TrType, '' AS clos, Trs_Del1_2.Coycode, Trs_Del2_2.OrdID,Trs_Del1_2.DocNo AS DcNo, Trs_Del1_2.Finyear AS DcFinyear, Trs_Del1_2.Dt AS DcDate,'TRANSFER OUT ' + RTRIM(CAST(dbo.OrderMas.Jobno AS varchar)) +     '/ ' + dbo.OrderMas.BuyOrdNo AS BuyerOrdNo, 0 AS PID, Mas_Dept_2.Deptname, Mas_Dept_2.DeptID,Trs_Del2_2.TranID AS StockId, Trs_Del2_2.BgRl, Trs_Del2_2.Kg, Trs_Del2_2.mtr, '' AS ProcessType,'P' as PartyUnit,Trs_Del1_2.DyeColId,Trs_Del1_2.designid, TrType As TransType,Trs_Del1_2.id,'N' as MultiGRN,'' As Remark,'' as name,0 as unit,isNull(Trs_Del1_2.SubPrsId,0) as SubPrsID FROM         dbo.Trs_Del1 AS Trs_Del1_2 INNER JOIN dbo.Trs_Del2 AS Trs_Del2_2 ON Trs_Del1_2.ID = Trs_Del2_2.ID INNER JOIN dbo.OrderMas ON Trs_Del2_2.TranOrdID = dbo.OrderMas.OrdId INNER JOIN dbo.Mas_Dept AS Mas_Dept_2 ON Trs_Del1_2.Prs_Dept = Mas_Dept_2.DeptID WHERE (Trs_Del1_2.TrType IN (3, 8)) /*Comment Break*/  


UNION ALL  SELECT     'SALES - ' AS TrType, Trs_Del1_1.Clos, Trs_Del1_1.Coycode, Trs_Del2_1.OrdId, Trs_Del1_1.DocNo AS DcNo, Trs_Del1_1.
Finyear, Trs_Del1_1.Dt AS DcDate, 'SALES ' + case when trs_del1_1.party=0 then MAs_buyer_1.buyername else Mas_Party_2.Pname end AS Expr1,case when trs_del1_1.party=0 then  Mas_Party_2.PID  else trs_del1_1.buyer end as PID, Mas_Dept_1.Deptname, Mas_Dept_1.
DeptID, Trs_Del2_1.StockID, Trs_Del2_1.BgRl, Trs_Del2_1.Kg, Trs_Del2_1.mtr, 'S' AS ProcessType,'P' as PartyUnit,Trs_Del1_1.DyeColId,Trs_Del1_1.designid, TrType As TransType,Trs_Del1_1.id,'N' as MultiGRN,'' As Remark,'' as name,0 as unit,isNull(Trs_Del1_1.SubPrsId,0) as SubPrsID FROM dbo.Trs_Del1 
AS Trs_Del1_1 INNER JOIN dbo.Trs_Del2 AS Trs_Del2_1 ON Trs_Del1_1.ID = Trs_Del2_1.ID left outer JOIN dbo.Mas_Party AS Mas_Party_2 ON Trs_Del1_1.Party = Mas_Party_2.PID INNER JOIN dbo.StockTable ON Trs_Del2_1.StockID = dbo.StockTable.StockID INNER JOIN dbo
.Mas_Dept AS Mas_Dept_1 ON dbo.StockTable.Dept = Mas_Dept_1.DeptID  left outer join  Mas_buyer Mas_buyer_1 on trs_del1_1.buyer= Mas_buyer_1.buyerid  WHERE(Trs_Del1_1.TrType = 2) /*Comment Break*/  

UNION ALL  SELECT     'GODOWN TRANSFER ' AS TrType, Trs_Del1_1.Clos, Trs_Del1_1.Coycode, Trs_Del2_1.OrdId, Trs_Del1_1.DocNo AS DcNo, Trs_Del1_1.Finyear,  Trs_Del1_1.Dt AS DcDate, 'GODOWN TRANSFER ' + Mas_Godown.GodName AS Expr1, Trs_Del1_1.Party, Mas_Dept_1.Deptname, Mas_Dept_1.DeptID, Trs_Del2_1.StockID, Trs_Del2_1.BgRl, Trs_Del2_1.Kg, Trs_Del2_1.mtr, '' AS ProcessType,'P' as PartyUnit,Trs_Del1_1.DyeColId,Trs_Del1_1.DesignId , TrType As TransType,Trs_Del1_1.id,'N' as MultiGRN,'' As Remark,'' as name,0 as unit,isNull(Trs_Del1_1.SubPrsId,0) as SubPrsID  FROM  Trs_Del1 AS Trs_Del1_1 INNER JOIN Trs_Del2 AS Trs_Del2_1 ON Trs_Del1_1.ID = Trs_Del2_1.ID  INNER JOIN StockTable ON Trs_Del2_1.StockID = StockTable.StockID INNER JOIN Mas_Dept AS Mas_Dept_1 ON StockTable.Dept = Mas_Dept_1.DeptID INNER JOIN Mas_Godown ON Trs_Del1_1.Party = Mas_Godown.GodID WHERE(Trs_Del1_1.TrType = 14)  /*Comment Break*/   
UNION ALL  SELECT 'DC' AS TrType, Trs_Del1.Clos, Trs_Del1.Coycode, Trs_Del2.OrdId,  Trs_Del1.DocNo AS DcNo, Trs_Del1.Finyear, Trs_Del1.Dt AS DcDate, Mas_Exporter.ExporterName  Pname,Trs_Del1.Party as PID, Mas_Dept.Deptname, Mas_Dept.DeptID, Trs_Del2.StockID, Trs_Del2.BgRl, Trs_Del2.Kg,Trs_Del2.mtr, Trs_Del1.ProcessType,Isnull(Trs_Del1.PartyUnit,'P') as PartyUnit,Trs_Del1.DyeColId,Trs_Del1.DesignId , TrType As TransType ,Trs_Del1.id,'N' as MultiGRN,'' As Remark,'' as name,0 as unit,isNull(Trs_Del1.SubPrsId,0) as SubPrsID  FROM  Trs_Del1 INNER JOIN Trs_Del2 ON Trs_Del1.ID = Trs_Del2.ID INNER JOIN Mas_Dept ON Trs_Del1.Prs_Dept = Mas_Dept.DeptID LEFT OUTER JOIN Mas_Party ON Trs_Del1.Party = Mas_Party.PID LEFT OUTER JOIN Mas_Exporter ON Trs_Del1.Party = Mas_Exporter.ExpID  WHERE  Trs_Del1.TrType IN (17)