/**
 * SPEC-M33 — the Code128 encoder, VERIFIED AGAINST AN INDEPENDENT
 * ENCODER: every module stream must be BYTE-IDENTICAL to python-barcode
 * 0.16.1's own Code128.build() output (tests/fixtures/code128-reference.json
 * — regenerated by scripts/gen_code128_fixture.py). The jsQR discipline,
 * 1D edition: our encoder's output is checked against another
 * implementation's output, not against itself.
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { code128Modules, code128Symbols, code128Svg } from '@/lib/erp/print/barcode'
import { PRINT_DOCS } from '@/lib/erp/print'
import { fetchBundleLabelsPrint, fetchBundleLabelPrint } from '@/lib/erp/print/fetchers-b'
import { allTools } from '@/lib/agent/tools'
import { db } from '@/lib/db'

const fixture = JSON.parse(
  readFileSync(join(__dirname, '../fixtures/code128-reference.json'), 'utf8'),
) as {
  patterns: string[]
  stop: string
  encodings: Record<string, string>
  valueB: Record<string, number>
}

/* ── a minimal independent DECODER (pattern table → symbols → text) ────── */
const byPattern = new Map(fixture.patterns.map((p, v) => [p, v]))
function decodeStream(stream: string): string | null {
  const STOP13 = fixture.stop + '11'
  if (!stream.endsWith(STOP13)) return null
  let s = stream.slice(0, -STOP13.length)
  const values: number[] = []
  while (s.length) {
    const v = byPattern.get(s.slice(0, 11))
    if (v === undefined) return null
    values.push(v)
    s = s.slice(11)
  }
  // values: [start, ...data(with checksum at the end)] — verify checksum too
  const checksum = values.pop()!
  let sum = values[0]
  values.slice(1).forEach((v, i) => (sum += (i + 1) * v))
  if (sum % 103 !== checksum) return null
  // walk code sets B/C and rebuild text
  let charset: 'B' | 'C' = values[0] === 105 ? 'C' : 'B'
  let text = ''
  for (const v of values.slice(1)) {
    if (v === 99) { charset = 'C'; continue }
    if (v === 100) { charset = 'B'; continue }
    if (charset === 'C') text += String(v).padStart(2, '0')
    else text += String.fromCharCode(v + 32)
  }
  return text
}

describe('SPEC-M33 — fixture parity (the independent-encoder gate)', () => {
  it('EVERY sample: our module stream is byte-identical to python-barcode', () => {
    const samples = Object.keys(fixture.encodings)
    expect(samples.length).toBeGreaterThanOrEqual(14)
    for (const text of samples) {
      expect(code128Modules(text), `parity failed for ${JSON.stringify(text)}`).toBe(fixture.encodings[text])
    }
  })

  it('the bundle-barcode contract format round-trips through the decoder', () => {
    const barcode = '*CUT0042B007*'
    expect(decodeStream(code128Modules(barcode))).toBe(barcode)
  })

  it('Code set B value identity: charCode − 32 for all printable ASCII', () => {
    for (let c = 32; c <= 126; c++) {
      const ch = String.fromCharCode(c)
      expect(ch.charCodeAt(0) - 32).toBe(fixture.valueB[ch])
    }
  })

  it('code-set paths: digit-leading text starts in C (START 105 first symbol)', () => {
    // '1234' → [105, 12, 34, checksum] — no B symbol at all
    const syms = code128Symbols('1234')
    expect(syms[0]).toBe(105)
    expect(syms[1]).toBe(12)
    expect(syms[2]).toBe(34)
  })

  it('the leading START_C + TO_C collapse: "99" → [105, checksum]', () => {
    const syms = code128Symbols('99')
    expect(syms).toEqual([105, 2]) // 105 % 103 = 2
  })
})

describe('SPEC-M33 — code128Svg (the label artifact)', () => {
  const BARCODE = '*CUT0001B001*'

  it('renders a self-contained SVG with quiet zones, crispEdges + human text', () => {
    const svg = code128Svg(BARCODE)
    expect(svg).toMatch(/^<svg /)
    expect(svg).toContain('shape-rendering="crispEdges"')
    expect(svg).toContain(`aria-label="barcode ${BARCODE}"`)
    expect(svg).toContain(`>${BARCODE}</text>`)
    // quiet zone: viewBox width = (modules + 20) * moduleWidth (default 2)
    const modules = code128Modules(BARCODE).length
    expect(svg).toContain(`width="${(modules + 20) * 2}"`)
    expect(svg.endsWith('</svg>')).toBe(true)
    expect(svg).not.toContain('http://www.w3.org/2000/svg/') // no external refs
  })

  it('showText:false drops the human-readable line', () => {
    expect(code128Svg(BARCODE, { showText: false })).not.toContain('<text')
  })

  it('honest fail: non-Code-B chars throw; empty input throws', () => {
    expect(() => code128Svg('café')).toThrow(/Code set B/)
    expect(() => code128Modules('')).toThrow(/empty/)
    expect(() => code128Modules('a\tb')).toThrow()
  })

  it('determinism: same input ⇒ byte-identical SVG', () => {
    expect(code128Svg(BARCODE)).toBe(code128Svg(BARCODE))
  })
})

/* ── fetcher + registry (service level) ─────────────────────────────────── */
const TS = String(Date.now()).slice(-8)
const ORDER_NO = `M33-SO-${TS}`
const CUT_NO = `M33-CUT-${TS}`
let cutOrderId = ''
let bundleIds: string[] = []

describe('SPEC-M33 — bundle label fetchers (the sticker sheet)', () => {
  beforeAll(async () => {
    const buyer = await db.buyer.create({ data: { code: `M33BY-${TS}`, name: `M33 Buyer ${TS}` } })
    const style = await db.style.create({ data: { styleNo: `M33ST-${TS}` } })
    const order = await db.order.create({
      data: { orderNo: ORDER_NO, buyerId: buyer.id, styleId: style.id, finYear: 'FY26', totalPcs: 250 },
    })
    const cut = await db.cutOrder.create({
      data: { cutNo: CUT_NO, orderId: order.id, fabricIssued: 180, totalPcs: 250, status: 'planned' },
    })
    cutOrderId = cut.id
    for (let i = 1; i <= 3; i++) {
      const b = await db.cutBundle.create({
        data: {
          cutOrderId: cut.id,
          bundleNo: `${CUT_NO}/B${i}`,
          barcode: `*${CUT_NO.replace(/[^A-Z0-9]/gi, '')}B${String(i).padStart(3, '0')}*`,
          qty: 100,
          status: 'in_cutting',
        },
      })
      bundleIds.push(b.id)
    }
  })

  afterAll(async () => {
    await db.cutBundle.deleteMany({ where: { id: { in: bundleIds } } })
    const cut = await db.cutOrder.findUnique({ where: { id: cutOrderId } })
    if (cut) {
      await db.cutOrder.delete({ where: { id: cutOrderId } }).catch(() => {})
      await db.order.delete({ where: { id: cut.orderId } }).catch(() => {})
    }
    await db.style.deleteMany({ where: { styleNo: `M33ST-${TS}` } })
    await db.buyer.deleteMany({ where: { code: `M33BY-${TS}` } })
    await db.$disconnect()
  })

  it('bundle-labels: one card per bundle, ordered, each with a Code128 SVG', async () => {
    const doc = await fetchBundleLabelsPrint(CUT_NO)
    expect(doc).not.toBeNull()
    expect(doc!.docType).toBe('bundle-labels')
    expect(doc!.title).toBe('BUNDLE LABELS')
    expect(doc!.docNo).toBe(CUT_NO)
    expect(doc!.labels).toHaveLength(3)
    expect(doc!.labels!.map((c) => c.heading)).toEqual([`${CUT_NO}/B1`, `${CUT_NO}/B2`, `${CUT_NO}/B3`])
    const card = doc!.labels![0]
    expect(card.barcode).toMatch(/^<svg /)
    expect(card.barcodeText).toBe(`*${CUT_NO.replace(/[^A-Z0-9]/gi, '')}B001*`)
    const meta = new Map(card.meta)
    expect(meta.get('Order')).toBe(ORDER_NO)
    expect(meta.get('Style')).toBe(`M33ST-${TS}`)
    expect(meta.get('Qty')).toBe('100 pcs')
  })

  it('bundle-labels resolves by db id too', async () => {
    const doc = await fetchBundleLabelsPrint(cutOrderId)
    expect(doc?.docNo).toBe(CUT_NO)
  })

  it('bundle-label (single reprint): resolves by bundleNo AND by barcode', async () => {
    const byNo = await fetchBundleLabelPrint(`${CUT_NO}/B2`)
    expect(byNo?.docType).toBe('bundle-label')
    expect(byNo?.labels).toHaveLength(1)
    expect(byNo?.labels![0].heading).toBe(`${CUT_NO}/B2`)
    const barcode = byNo!.labels![0].barcodeText
    const byBarcode = await fetchBundleLabelPrint(barcode)
    expect(byBarcode?.docNo).toBe(`${CUT_NO}/B2`)
  })

  it('unknown cut / bundle → null (honest 404 path)', async () => {
    expect(await fetchBundleLabelsPrint('CUT-9999')).toBeNull()
    expect(await fetchBundleLabelPrint('CUT-9999/B1')).toBeNull()
    expect(await fetchBundleLabelPrint('*NOPE*')).toBeNull()
  })

  it('both docTypes are registered in PRINT_DOCS', () => {
    expect(typeof PRINT_DOCS['bundle-labels']).toBe('function')
    expect(typeof PRINT_DOCS['bundle-label']).toBe('function')
  })

  it('get_bundle tool registered (read, cutting) — 229 → 230 after M31', async () => {
    const tool = allTools.find((t) => t.name === 'get_bundle')
    expect(tool).toBeDefined()
    expect(tool!.domain).toBe('cutting')
    expect(tool!.isWrite).toBe(false)
    expect(allTools.length).toBe(246) // M42 INV: +create_stock_take +record_stock_counts +advance_stock_take (M39 JWL: +bill_jobwork +list_jobworker_statement)
    // resolves a real bundle by bundleNo (the scan reflex)
    const res = await tool!.execute({ bundle: `${CUT_NO}/B1` })
    expect(res.text).toContain(`${CUT_NO}/B1`)
    expect(JSON.stringify(res.json)).toContain('labelPrint')
    // and by barcode
    const byBarcode = await tool!.execute({ bundle: `*${CUT_NO.replace(/[^A-Z0-9]/gi, '')}B001*` })
    expect(byBarcode.text).toContain(`${CUT_NO}/B1`)
    // honest miss
    const miss = await tool!.execute({ bundle: 'CUT-9999/B1' })
    expect(miss.text).toContain('No bundle matches')
  })
})

/* ── source pins (the surfaces stay wired) ──────────────────────────────── */
describe('SPEC-M33 — surface source pins', () => {
  const read = (p: string) => readFileSync(join(__dirname, '../..', p), 'utf8')

  it('PrintSheet renders the label-card grid when labels present', () => {
    const src = read('src/components/erp/print-sheet.tsx')
    expect(src).toContain('data-testid="label-cards"')
    expect(src).toContain('doc.labels')
    expect(src).toContain('card.barcode')
    expect(src).toContain('card.barcodeText')
  })

  it('cut-order view carries the Print bundle labels door', () => {
    const src = read('src/app/(erp)/cutting/job-order/[id]/page.tsx')
    expect(src).toContain('docType="bundle-labels"')
    expect(src).toContain('Print bundle labels')
  })

  it('PrintDoc type carries PrintLabelCard', () => {
    const src = read('src/lib/erp/print/types.ts')
    expect(src).toContain('PrintLabelCard')
    expect(src).toContain('labels?: PrintLabelCard[]')
  })

  it('the encoder table was generated from the fixture, never hand-typed', () => {
    // the parity test above IS the gate; this pin documents the lesson
    const src = read('src/lib/erp/print/barcode.ts')
    expect(src).toContain('NEVER hand-typed')
  })
})
